esrlabs/chipmunk

- app/build.json
- app/client/src/app/core/handles/handle.open.serial.stream.ts
- app/client/src/app/core/modules/controller.data.stream.ts
- app/client/src/app/core/modules/controller.localsettings.ts
- app/client/src/app/views/search.results/search.request/component.ts
- correction of detection broken line in output
- autofocus for switching between search and terminal modes (on search line)
- saving commands for terminal out scope of session
> Corrections

- app/build.json
- app/client/src/app/core/api/api.commands.ts
- app/client/src/app/core/handles/handle.open.adblogcat.stream.ts
- app/server/libs/api.commands.js
- app/server/libs/service.adb.js
- app/server/libs/tools.spawn.js
Show Android devices list, if connected more than one device
> Android devices list

- app/build.json
- app/client/src/app/config/settings.json
- app/client/src/app/core/components/common/dialogs/app.settings/visual/component.ts
- app/client/src/app/core/components/common/dialogs/app.settings/visual/template.html
- app/client/src/app/core/modules/controller.settings.ts
- app/client/src/app/views/list/line/styles.less
- app/client/src/app/views/list/line/template.html
- app/client/src/app/views/search.results/component.ts
- app/client/src/app/views/search.results/search.request/component.ts
- app/client/src/app/views/search.results/search.request/template.html
- fix an issue with refreshing main view after visual settings were updated
- auto deactivate predefined filters on a new search request
- fix an issue with hide/show popup on results-line in the main view
> Fixes & updates

- app/build.json
- app/client/src/app/core/components/common/input/component.ts
- app/client/src/app/core/components/common/input/styles.less
- app/client/src/app/core/components/common/input/template.html
- app/client/src/app/core/components/holder/view-bar/styles.less
- app/client/src/app/core/handles/handle.open.serial.stream.ts
- app/client/src/app/core/modules/tools.htmlserialize.ts
- app/client/src/app/core/modules/tools.regexp.ts
- app/client/src/app/views/list/component.ts
- app/client/src/app/views/list/full-line/component.ts
- app/client/src/app/views/list/item/component.ts
- app/client/src/app/views/list/template.html
- app/client/src/app/views/search.results/search.request/component.ts
- app/client/src/app/views/search.results/search.request/interface.extrabutton.ts
- app/client/src/app/views/search.results/search.request/styles.less
- app/client/src/app/views/search.results/search.request/template.html
- app/client/src/app/workers/data.processor.strings.ts
- fix an issue with search (using JS native object properties names: constructor, prototype, ...)
- fix style issue with view-bar icons
- fix an issue with switching on full line view (in main output)
- provide a saving of history of search requests
- provide a saving of history of the serial port commands
> Fix & Features

- app/build.json
- app/client/src/app/core/components/common/dialogs/terminal.open/component.ts
- app/client/src/app/core/handles/handle.open.serial.stream.ts
- app/client/src/app/core/handles/handle.open.telnet.stream.ts
- app/client/src/app/core/handles/handle.open.terminal.stream.ts
- app/client/src/app/views/search.results/search.request/component.ts
- app/client/src/app/views/search.results/search.request/interface.extrabutton.ts
- app/client/src/app/views/search.results/search.request/styles.less
- app/client/src/app/views/search.results/search.request/template.html
- fixed bug with a history of terminal commands; serial port commands.
- added titles for an extended functionality of search bar (highlight type of input)
- added shortcuts:
a) shift + up / shift + down: switch search bar between modes: search / extended functionality
b) ctrl + enter (in extended functionality): do command and back to search functionality.
(*) extended functionality: search bar can be used for sending commands via terminal/telnet/serial port. It's available if the stream is opened.
> Fixes and features

- .travis.yml
This pull request adds a job definition to build and publish chipmunk versions for osx and linux
> Add .travis.yml job definition for OSx and Linux

- .travis.yml
Fix error on .travis.yml and add windows build
> Add windows build

- rakefile.rb
> [#468](feat) script to generate list of files/folders in release

- application/client.plugins/projects/processes/package.json
- application/sandbox/processes/process/package.json
- application/sandbox/processes/process/src/service.streams.ts
> [#343](fix) using $HOME as default cwd for processes plugin

- .github/workflows/release.yml
- .gitignore
- application/client.libs/logviewer.client.components/projects/logviewer-client-containers/logviewer-client-containers
- application/electron/package.json
- rakefile.rb
rake tasks for linting and creating tagged releases
fix move of final delivery to folder
remove unused files when deploying
fix build for windows
install missing dependencies for neon build
make sure correct python version is installed on windows
vs 2015 install for windows since the default hangs
rake task to prepare neon builds with cargo config on windows
remove unused file
rake task polish
> [#71](chore): workflows with github actions

- application/client.core/src/app/environment/components/views/chart/chart/component.ts
- application/client.core/src/app/environment/components/views/chart/service.data.ts
- application/client.core/src/app/environment/components/views/chart/zoomer/component.ts
- application/client.core/src/app/environment/components/views/chart/zoomer/cursor/component.ts
- application/client.core/src/app/environment/components/views/chart/zoomer/cursor/styles.less
- application/client.core/src/app/environment/components/views/chart/zoomer/cursor/template.html
- application/client.core/src/app/environment/components/views/chart/zoomer/template.html
- application/sandbox/dlt-render/render/package.json
* fix issue for case: width of chart area > size of stream
* fix issue for case: width of chart area > selection in stream
* updated zoom-cursor view
* reverse zoom wheel
> Chart issues

- application/client.core/src/app/environment/components/views/chart/chart/component.ts
- application/client.core/src/app/environment/components/views/output/map/component.ts
- application/client.core/src/app/environment/components/views/search/output/component.ts
- application/client.core/src/app/environment/controller/controller.session.tab.map.ts
- application/client.core/src/app/environment/controller/controller.session.tab.stream.bookmarks.ts
- application/client.core/src/app/environment/layout/state.ts
- application/client.core/src/app/environment/services/service.sessions.tabs.ts
- application/client.plugins/package-lock.json
- application/client.plugins/package.json
- application/electron/package.json
- application/electron/src/services/service.hotkeys.ts
* fixed plugin's sessions events hub (no more repeated events)
* fixed bookmarks hotkeys navigation
* fixed handling resizing of chart
* scroll the main view by click on marker's bar
* expand filters on marker's bar on dblclick
> Features & Fixes

- application/apps/indexer-neon/native/Cargo.lock
- application/apps/indexer-neon/native/src/channels.rs
- application/apps/indexer-neon/native/src/dlt_indexer_channel.rs
- application/apps/indexer/Cargo.lock
- application/apps/indexer/dlt/Cargo.toml
- application/apps/indexer/dlt/src/dlt.rs
- application/apps/indexer/dlt/src/dlt_parse.rs
- application/apps/indexer/dlt/src/fibex.rs
- application/apps/indexer/dlt/src/lib.rs
- application/apps/indexer/dlt/src/tests/dlt_parse_tests.rs
- application/apps/indexer/dlt/src/tests/fibex_tests.rs
- application/apps/indexer/dlt/src/tests/mod.rs
- application/apps/indexer/dlt/tests/dlt-messages.xml
- application/apps/indexer/indexer_cli/src/main.rs
> Add fibex support for nonverbose DLT mode

- application/client.plugins/projects/serial/src/lib/common/host.events.ts
- application/client.plugins/projects/serial/src/lib/common/interface.portinfo.ts
- application/client.plugins/projects/serial/src/lib/module.ts
- application/client.plugins/projects/serial/src/lib/services/service.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/styles.less
- application/client.plugins/projects/serial/src/lib/views/dialog/template.html
- application/client.plugins/projects/serial/src/lib/views/dialog/titlebar/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/titlebar/template.html
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/component.ts
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/port.connected/component.ts
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/port.connected/template.html
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/port.listed/component.ts
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/port.listed/template.html
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/styles.less
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/template.html
- application/client.plugins/projects/serial/src/public_api.ts
- application/client.plugins/theme/colors.less
- application/electron/package.json
- application/electron/src/services/service.plugins.ts
- application/sandbox/serial/process/package.json
- application/sandbox/serial/process/src/consts/commands.ts
- application/sandbox/serial/process/src/consts/events.ts
- application/sandbox/serial/process/src/controllers/controller.serialport.ts
- application/sandbox/serial/process/src/controllers/controller.session.ts
- application/sandbox/serial/process/src/main.ts
- application/sandbox/serial/process/src/services/service.ports.ts
- application/sandbox/serial/process/src/services/service.sessions.ts
- application/sandbox/serial/render/lib/common/host.events.d.ts
- application/sandbox/serial/render/lib/views/sidebar.vertical/component.d.ts
**- Popup window**
- Show available ports
- Show activity of ports
- Connect to ports
- Button to open popup on upper bar
**- Send to port**
- Send message to port
- Choose port to send to from dropdown list
**- Session**
- Session remembers which port was selected on dropdown list
- Single mode supported
> Serial port upgrade

- application/client.plugins/package.json
- application/client.plugins/projects/serial/package.json
- application/client.plugins/projects/serial/src/lib/module.ts
- application/client.plugins/projects/serial/src/lib/services/service.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/styles.less
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/template.html
- application/client.plugins/projects/serial/src/lib/views/dialog/styles.less
- application/client.plugins/projects/serial/src/lib/views/dialog/template.html
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/component.ts
- application/sandbox/serial/process/package.json
- application/sandbox/serial/process/src/controllers/controller.session.ts
- application/sandbox/serial/render/package.json
Create Sparklines for serial port plugin to show activity on popup window for available ports
> Sparkline integration

- application/client.plugins/projects/serial/src/lib/services/service.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/styles.less
- application/client.plugins/projects/serial/src/lib/views/dialog/port.available/template.html
- application/client.plugins/projects/serial/src/lib/views/dialog/template.html
- application/client.plugins/projects/serial/src/lib/views/dialog/titlebar/components.ts
- application/client.plugins/projects/serial/src/lib/views/dialog/titlebar/template.html
- application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/component.ts
- application/sandbox/serial/process/src/main.ts
- application/sandbox/serial/process/src/services/service.sessions.ts
- application/sandbox/serial/process/src/test.ts
**New features:**
- create new line in output window
- button to connect to recently connected ports (session only)
- double click connect to port
**Fixes:**
- spy stop when window is closed
- resolve issue with error messages in test port implementation
**Refactoring:**
- 'connected' alignment to the right
> Small serial plugin changes (features, fixes and refactoring)

- application/client.core/src/app/environment/components/dialogs/file.options.dlt/component.ts
- application/client.core/src/app/environment/components/dialogs/file.options.dlt/stats/component.ts
- application/client.core/src/app/environment/components/dialogs/file.options.dlt/stats/styles.less
- application/client.core/src/app/environment/components/dialogs/file.options.dlt/stats/template.html
- application/client.core/src/app/environment/components/dialogs/file.options.dlt/styles.less
- application/client.core/src/app/environment/components/dialogs/file.options.dlt/template.html
- application/client.core/src/app/environment/components/dialogs/module.ts
- application/client.core/src/app/environment/controller/file.options/controller.file.dlt.ts
- application/client.core/src/app/environment/directives/material.autocomplete.directive.ts
- application/client.core/src/app/environment/theme/material.less
- application/client.core/src/app/environment/theme/reset.less
- application/client.libs/chipmunk.client.components/projects/chipmunk-client-primitive/src/lib/ddlists/standard/styles.less
> Refactoring

- .github/workflows/release_master.yml
- rakefile.rb
Fixing issues with code signing and notarising on OSX
> Fixed signing for OSX

- application/apps/indexer/dlt/src/fibex.rs
> Add support for enums

- application/apps/indexer-neon/native/src/export_channel.rs
- application/apps/indexer-neon/native/src/lib.rs
- application/apps/indexer-neon/native/src/timestamp_detector_channel.rs
- application/apps/indexer-neon/rakefile.rb
- application/apps/indexer-neon/src/processor.ts
- application/apps/indexer-neon/src/progress.ts
- application/apps/indexer-neon/src/tests.ts
- application/apps/indexer/processor/src/parse.rs
- application/apps/launch_and_update/base/src/util.rs
- application/client.core/src/app/environment/components/sidebar/merge/component.ts
- application/common/interfaces/index.ts
- application/common/interfaces/interface.detect.ts
- application/common/ipc/electron.ipc.messages/merge.files.discover.response.ts
- application/electron/src/controllers/features/merge/merge.discover.ts
in addition to the timestamp format, the regular expression
is returned (including groups)
> Implement new interface for representing timestamp formats

- application/apps/indexer-neon/native/src/channels.rs
- application/apps/indexer-neon/native/src/dlt_indexer_channel.rs
- application/apps/indexer-neon/native/src/dlt_stats_channel.rs
- application/apps/indexer-neon/native/src/format_verify_channel.rs
- application/apps/indexer-neon/native/src/indexer_channel.rs
- application/apps/indexer-neon/native/src/lib.rs
- application/apps/indexer-neon/native/src/timestamp_detector_channel.rs
- application/apps/indexer-neon/rakefile.rb
- application/apps/indexer-neon/src/emitter.ts
- application/apps/indexer-neon/src/index.ts
- application/apps/indexer-neon/src/merger.ts
- application/apps/indexer-neon/src/processor.ts
- application/apps/indexer-neon/src/progress.ts
- application/apps/indexer-neon/src/tests.ts
- application/apps/indexer/dlt/src/dlt.rs
- application/apps/indexer/dlt/src/dlt_file.rs
- application/apps/indexer/dlt/src/dlt_parse.rs
- application/apps/indexer/dlt/src/tests/dlt_file_tests.rs
- application/apps/indexer/dlt/src/tests/dlt_parse_tests.rs
- application/apps/indexer/indexer_base/src/progress.rs
- application/apps/indexer/indexer_cli/src/main.rs
- application/apps/indexer/merging/src/concatenator.rs
- application/apps/indexer/merging/src/merger.rs
- application/apps/indexer/processor/src/parse.rs
- application/apps/indexer/processor/src/processor.rs
- application/apps/indexer/processor/src/tests/parse_tests.rs
- application/apps/indexer/processor/src/tests/processor_tests.rs
> Api updates

- application/client.core/src/app/environment/components/dialogs/multiplefiles/component.ts
- application/client.core/src/app/environment/components/dialogs/multiplefiles/template.html
- application/client.core/src/app/environment/components/sidebar/concat/component.ts
- application/client.core/src/app/environment/components/sidebar/merge/component.ts
- application/client.core/src/app/environment/components/views/output/component.ts
- application/client.core/src/app/environment/controller/controller.file.storage.ts
- application/client.core/src/app/environment/layout/area.primary/no-tabs-content/component.ts
- application/client.core/src/app/environment/services/service.file.concat.ts
- application/client.core/src/app/environment/services/service.file.merge.ts
- application/client.core/src/app/environment/services/service.file.opener.ts
- application/client.core/src/app/environment/services/shared.services.sidebar.ts
- application/common/ipc/electron.ipc.messages/file.list.response.ts
- application/common/ipc/electron.ipc.messages/index.ts
- application/electron/package.json
- application/electron/src/services/files/service.file.opener.ts
- application/electron/src/tools/fs.ts
Ability to select files when drag&dropped with checkboxes
Problematic files (no access, etc.) will be disabled by default
Hidden files will be unchecked by default
Ability to drag&drop additional files when dialog window open
> [#808](feat) Drag&Drop improvement

- application/electron/src/services/files/service.file.opener.ts
- versions.json
> Update versions and fix for 817

- application/client.core/src/app/environment/components/views/search/component.ts
- application/client.core/src/app/environment/components/views/search/template.html
- application/electron/src/controllers/electron/menu.functions/handler.item.about.ts
- application/electron/src/services/files/service.file.opener.ts
- Disable the checkbox for empty files when drag&drop multiple files in the dialog window
- support TAB when selecting recently used search terms
- Fix release version detection for Linux and Mac OS
> Solution for [#745][#665][#797]

- application/client.libs/chipmunk.client.components/projects/chipmunk-client-material/src/lib/tabs/list/component.ts
- application/client.libs/chipmunk.client.components/projects/chipmunk-client-material/src/lib/tabs/list/styles.less
- rakefile.rb
- Fix for issue #877 
- Remove padding on right side of tab
- Add new rake command to build chipmunk.client.components and deliver it to client
> Fix for arrow bug on tabs

- rake-plugins.rb
Get rid of calling URI module 
Related to #962
> Fix rakefile

- application/electron/src/services/service.env.ts
> Do not lock starting of app on OS env issue (close #979)

- application/apps/indexer-neon/src/api/dlt.ts
- application/apps/indexer-neon/src/tests.ts
- application/apps/indexer/dlt/src/dlt_net.rs
- application/apps/indexer/indexer_base/src/config.rs
- application/apps/indexer/indexer_cli/src/main.rs
- application/client.core/src/app/environment/components/sidebar/dlt.connector/component.ts
- application/client.core/src/app/environment/components/sidebar/dlt.connector/state.error.ts
- application/client.core/src/app/environment/components/sidebar/dlt.connector/template.html
- application/client.core/src/app/environment/services/service.electron.ipc.ts
- application/common/ipc/electron.ipc.messages/dlt.deamon.connect.request.ts
- application/common/ipc/electron.ipc.messages/dlt.deamon.recent.response.ts
- application/common/ipc/electron.ipc.messages/index.ts
- application/electron/src/controllers/connections/dlt.connection.ts
- application/electron/src/services/connectors/service.dlt.deamon.ts
> [#703](feat) DLT connector: support for IPv6 (UI)

- application/client.core/src/app/environment/components/sidebar/shell/module.ts
- application/client.core/src/app/environment/components/sidebar/shell/running/template.html
- application/client.core/src/app/environment/components/sidebar/shell/services/service.ts
- application/client.core/src/app/environment/components/sidebar/shell/template.html
- application/client.core/src/app/environment/components/sidebar/shell/terminated/component.ts
- application/client.core/src/app/environment/components/sidebar/shell/terminated/styles.less
- application/client.core/src/app/environment/components/sidebar/shell/terminated/template.html
- application/common/ipc/electron.ipc.messages/index.ts
- application/common/ipc/electron.ipc.messages/shell.process.stopped.event.ts
- application/common/ipc/electron.ipc.messages/shell.process.terminated.list.request.ts
- application/common/ipc/electron.ipc.messages/shell.process.terminated.list.response.ts
- application/electron/src/controllers/stream.shell/controller.process.ts
- application/electron/src/controllers/stream.shell/controller.ts
- Add panel for finished/terminated processes
- Swap places of input panel and running panel
- Show runtime of terminated process on hovering
> Add terminated panel

- application/client.core/package-lock.json
- application/client.core/package.json
- application/client.core/src/app/environment/components/views/row/component.ts
- application/client.libs/chipmunk.client.toolkit/package-lock.json
- application/client.libs/chipmunk.client.toolkit/package.json
- application/client.libs/chipmunk.client.toolkit/src/controllers/controller.viewport.events.ts
- versions.json
> Give source meta data on row-click

- application/electron/package-lock.json
- application/electron/package.json
- application/electron/src/controllers/files.parsers/file.parser.text.ts
- application/electron/src/controllers/plugins/plugin.installed.ts
- application/electron/src/controllers/plugins/plugins.store.ts
- application/electron/src/main.ts
- application/electron/src/services/cli/cli.action.concat.ts
- application/electron/src/services/cli/cli.action.merge.ts
- application/electron/src/services/service.env.ts
- application/electron/src/services/service.network.ts
- application/electron/src/services/service.update.ts
- application/electron/src/tools/env.github.client.ts
- application/electron/src/tools/env.net.ts
- application/electron/tsconfig.json
> Add proxy settings

- application/client.core/src/app/environment/components/sidebar/shell/environment/template.html
- application/client.core/src/app/environment/components/sidebar/shell/input/preset/component.ts
- Fix loading of environment variables
- empty input after creating a preset
- focus on input when editing exisiting environment values/variables
> Shell fixes

- CHANGELOG.md
- application/electron/package.json
- application/node.libs/chipmunk.shell.env/package-lock.json
- application/node.libs/chipmunk.shell.env/package.json
- application/node.libs/chipmunk.shell.env/spec/env.spec.ts
- application/node.libs/chipmunk.shell.env/spec/support/jasmine.json
- application/node.libs/chipmunk.shell.env/src/index.ts
- application/node.libs/chipmunk.shell.env/src/powershell.ts
- application/node.libs/chipmunk.shell.env/src/profiles.ts
- application/node.libs/chipmunk.shell.env/src/symlink.ts
> Correct detecting of available profiles on windows

- application/client.core/package.json
- application/client.core/src/app/environment/components/complex/popups/component.ts
- application/client.core/src/app/environment/components/complex/popups/popup/component.ts
- application/client.core/src/app/environment/controller/session/dependencies/comments/session.dependency.comments.ts
- application/client.libs/chipmunk.client.components/package-lock.json
- application/client.libs/chipmunk.client.toolkit/package.json
- application/client.libs/chipmunk.client.toolkit/src/interfaces/client.popup.ts
> Fix edit/update comments workflow

- application/client.core/src/app/environment/components/sidebar/adb/component.ts
- application/client.core/src/app/environment/components/sidebar/adb/logcat/component.ts
- application/client.core/src/app/environment/components/sidebar/adb/logcat/styles.less
- application/client.core/src/app/environment/components/sidebar/adb/logcat/template.html
- application/client.core/src/app/environment/components/sidebar/adb/module.ts
- application/client.core/src/app/environment/components/sidebar/adb/services/service.ts
- application/client.core/src/app/environment/components/sidebar/adb/styles.less
- application/client.core/src/app/environment/components/sidebar/adb/template.html
- application/client.core/src/app/environment/components/sidebar/module.ts
- application/client.core/src/app/environment/services/service.sessions.tabs.ts
- application/client.core/src/app/environment/states/state.default.sidebar.apps.ts
- application/common/interfaces/index.ts
- application/common/interfaces/interface.adb.ts
- application/common/ipc/electron.ipc.messages/adb.devices.request.ts
- application/common/ipc/electron.ipc.messages/adb.devices.response.ts
- application/common/ipc/electron.ipc.messages/adb.load.request.ts
- application/common/ipc/electron.ipc.messages/adb.load.response.ts
- application/common/ipc/electron.ipc.messages/adb.processes.request.ts
- application/common/ipc/electron.ipc.messages/adb.processes.response.ts
- application/common/ipc/electron.ipc.messages/adb.start.request.ts
- application/common/ipc/electron.ipc.messages/adb.start.response.ts
- application/common/ipc/electron.ipc.messages/adb.stop.request.ts
- application/common/ipc/electron.ipc.messages/adb.stop.response.ts
- application/common/ipc/electron.ipc.messages/adb.stream.updated.ts
- application/common/ipc/electron.ipc.messages/index.ts
- application/electron/src/controllers/stream.adb/controller.process.ts
- application/electron/src/controllers/stream.adb/controller.ts
- application/electron/src/controllers/stream.adb/postman.ts
- application/electron/src/services/service.streams.ts
[#193](feat) Back-end implementation for logcat
[#193](feat) Front-end implementation of logcat
[#193](feat) New features
[#193](refact) Small refactoring
[#193](feat) Show received amount; small fixes
> Adb logcat implementation

- application/client.core/src/app/environment/components/sidebar/adb/directives/scrollIntoView.directive.ts
- application/client.core/src/app/environment/components/sidebar/adb/logcat/component.ts
- application/client.core/src/app/environment/components/sidebar/adb/logcat/styles.less
- application/client.core/src/app/environment/components/sidebar/adb/logcat/template.html
- application/client.core/src/app/environment/components/sidebar/adb/module.ts
- application/client.core/src/app/environment/components/sidebar/adb/services/service.ts
- application/client.core/src/app/environment/theme/text.less
- application/electron/src/controllers/stream.adb/controller.ts
- refresh buttons for processes and devices
- filter functionality for processes
> Adb enhancement

- application/client.core/src/app/environment/components/dialogs/filters.load/component.ts
- application/client.core/src/app/environment/components/dialogs/filters.load/styles.less
- application/client.core/src/app/environment/components/dialogs/filters.load/template.html
- application/client.core/src/app/environment/components/dialogs/module.ts
- application/client.core/src/app/environment/components/sidebar/search.manager/component.ts
- application/client.core/src/app/environment/components/sidebar/search.manager/controls/component.ts
- application/client.core/src/app/environment/components/sidebar/search.manager/controls/styles.less
- application/client.core/src/app/environment/components/sidebar/search.manager/controls/template.html
- application/client.core/src/app/environment/components/sidebar/search.manager/module.ts
- application/client.core/src/app/environment/components/sidebar/search.manager/template.html
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/charts/controller.session.tab.search.charts.storage.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/disabled/controller.session.tab.search.disabled.storage.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/disabled/controller.session.tab.search.disabled.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/filters/controller.session.tab.search.filters.storage.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/filters/controller.session.tab.search.filters.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/store/controller.session.tab.search.store.support.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/store/controller.session.tab.search.store.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/timeranges/controller.session.tab.search.ranges.storage.ts
- application/client.core/src/app/environment/controller/session/dependencies/search/dependencies/timeranges/controller.session.tab.search.ranges.ts
Give the search UI a new look by removing the "Manage" section making it look lighter.
Now when the user has some filters stored and loads a new file with filters they will be warned and have the options to cancel, replace the filters or even append the current filters with the new ones
> Rework sidebar Search UI and issue warning

- application/client.core/src/app/environment/components/views/chart/styles.less
- application/electron/src/controllers/electron/controller.electron.menu.ts
- mouse pointer turns into crosshair in charts area
- add feature to zoom in and out
- "Edit" application menu removed completely (functionality stays)
> Small fixes/refactoring

- application/apps/indexer/Cargo.lock
- application/apps/indexer/indexer_base/src/export.rs
- application/apps/indexer/indexer_base/src/utils.rs
- application/apps/indexer/indexer_cli/Cargo.toml
- application/apps/indexer/indexer_cli/src/interactive.rs
- application/apps/indexer/indexer_cli/src/main.rs
- application/apps/indexer/merging/src/concatenator.rs
- application/apps/indexer/merging/src/merger.rs
- application/apps/indexer/processor/src/processor.rs
- application/apps/indexer/processor/src/text_source.rs
- application/apps/indexer/session/src/state.rs
- application/apps/indexer/sources/src/pcap/file.rs
- application/apps/rustcore/rs-bindings/src/js/session/mod.rs
- application/apps/rustcore/rs-bindings/src/logging.rs
refactor indexer_cli to use structopt
> switch from clap to structopt

- README.md
I added chipmunk to Homebrew cask repo.
So user can install using Homebrew
https://github.com/Homebrew/homebrew-cask/pull/133440
> docs: update macos install method

- application/client/src/app/ui/views/dialogs/about/module.ts
- application/client/src/app/ui/views/dialogs/hotkeys/module.ts
- application/client/src/app/ui/views/dialogs/module.ts
- application/client/src/app/ui/views/module.ts
- application/holder/package.json
- fix for bootstrap on client side
> Version up to 3.3.3

- application/client/src/app/service/session/dependencies/search.ts
- application/client/src/app/ui/views/toolbar/chart/abstract/advanced.ts
- application/client/src/app/ui/views/toolbar/chart/abstract/basic.ts
- application/client/src/app/ui/views/toolbar/chart/chart/state.ts
- application/client/src/app/ui/views/toolbar/chart/chart/styles.less
- application/client/src/app/ui/views/toolbar/chart/chart/template.html
- application/client/src/app/ui/views/toolbar/chart/styles.less
- application/client/src/app/ui/views/toolbar/chart/zoomer/cursor/state.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/state.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/styles.less
- application/client/src/app/ui/views/toolbar/chart/zoomer/template.html
- #1568 
- Enhanced crosshair for better orientation in chart view
> Chart Features and fixes

- application/client/src/app/ui/views/toolbar/chart/abstract/advanced.ts
- application/client/src/app/ui/views/toolbar/chart/chart/state.ts
- application/client/src/app/ui/views/toolbar/chart/chart/styles.less
- application/client/src/app/ui/views/toolbar/chart/chart/template.html
- application/client/src/app/ui/views/toolbar/chart/zoomer/state.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/template.html
[](refact) Proper error message output
[](refact) Refactor and fixes
[](refact) Refactor changes
> Chart fix + refactor

- application/apps/precompiled/updater/src/main.rs
- application/client/src/app/ui/elements/tree/scheme.ts
- application/client/src/app/ui/elements/tree/state.ts
- application/client/src/app/ui/elements/tree/styles.less
- application/client/src/app/ui/elements/tree/template.html
- application/client/src/app/ui/layout/workspace/no-tabs-content/template.html
- application/holder/package.json
- addition logs for updater
- update tree-component
- fix typos
> Fixes / Updates

- application/apps/rustcore/ts-bindings/spec/defaults.json
- application/apps/rustcore/ts-bindings/spec/session.map.spec.ts
- application/client/src/app/ui/styles/colors.ts
- application/client/src/app/ui/views/toolbar/chart/abstract/advanced.ts
- application/client/src/app/ui/views/toolbar/chart/abstract/basic.ts
- application/client/src/app/ui/views/toolbar/chart/chart/component.ts
- application/client/src/app/ui/views/toolbar/chart/chart/state.ts
- application/client/src/app/ui/views/toolbar/chart/service.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/cursor/state.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/state.ts
- application/client/src/app/ui/views/toolbar/chart/zoomer/styles.less
- application/client/src/app/ui/views/workspace/map/state.ts
- Enable scrolling in chart main view #1600 
- Adjust chart rectangle
- New test cases for mapping
- Add new validation for filter change #1618
> Chart fixes and refactor

- application/client/src/app/service/history/collection.disabled.ts
- application/client/src/app/service/history/collection.filters.ts
- application/client/src/app/service/session/dependencies/search.ts
- application/client/src/app/service/session/dependencies/search/store.ts
- application/client/src/app/ui/views/sidebar/search/filters/provider.ts
- application/holder/package.json
- fixing search triggering on restoring recent filters
> Master fix 001

- application/client/src/app/service/actions.ts
- application/client/src/app/service/actions/file.any.ts
- application/client/src/app/service/actions/folder.any.ts
- application/client/src/app/service/actions/folder.dlt.ts
- application/client/src/app/service/actions/folder.pcap.ts
- application/client/src/app/service/actions/folder.text.ts
- application/client/src/app/service/actions/index.ts
- application/client/src/app/service/actions/serial.text.ts
- application/client/src/app/service/actions/stream.dlt.custom.ts
- application/client/src/app/service/actions/stream.text.custom.ts
- application/client/src/app/service/actions/updates.ts
- application/client/src/app/service/bridge.ts
- application/client/src/app/ui/elements/scrollarea/row/styles.less
- application/client/src/app/ui/layout/workspace/no-tabs-content/component.ts
- application/client/src/app/ui/layout/workspace/no-tabs-content/template.html
- application/client/src/app/ui/views/toolbar/search/input/component.ts
- application/holder/src/env/fs/index.ts
- application/holder/src/service/actions/index.ts
- application/holder/src/service/actions/updates.ts
- application/holder/src/service/electron/dialogs.ts
- application/holder/src/service/menu.ts
- application/holder/src/service/updater.ts
- application/platform/ipc/request/actions/index.ts
- application/platform/ipc/request/actions/updates.ts
- application/platform/ipc/request/system/check_updates.ts
- application/platform/ipc/request/system/index.ts
- rearrange menu
- change menu behind 3 home screen buttons
- fix row's signatures (numbers)
- fix UI updating during search
> UI Updates & Fixes

- application/apps/indexer/session/src/handlers/observing/mod.rs
- application/apps/indexer/session/src/state/indexes/controller.rs
- application/apps/indexer/session/src/state/indexes/keys.rs
- application/apps/indexer/session/src/state/indexes/map.rs
- application/apps/indexer/session/src/state/indexes/mod.rs
- application/apps/indexer/session/src/state/indexes/tests_map_performance.rs
- application/apps/indexer/session/src/state/mod.rs
- application/apps/indexer/session/src/state/session_file.rs
- application/client/src/app/schema/content/row.ts
- application/client/src/app/ui/elements/scrollarea/row/template.html
- application/client/src/app/ui/views/toolbar/search/results/backing.ts
- application/holder/package.json
- fix updating an indexed map on change of stream len
- remove breadcrumb separator from main view
- fix calculation of count of hidden rows
> Up to 3.5.0

- application/client/src/app/ui/layout/component.ts
- application/client/src/app/ui/views/toolbar/search/input/styles.less
- application/client/src/app/ui/views/toolbar/search/input/template.html
- application/holder/package.json
> Up to 3.5.1

- .github/workflows/release_next.yml
- application/holder/package.json
> Update windows workflow

- .github/workflows/release_next.yml
- application/holder/package.json
> Update windows workflow (testing)

- .github/workflows/release_next.yml
- application/holder/package.json
> Windows workflow update (testing)

- README.md
- contribution.md
Added contribution guide for new user.
> Add contribution guide.

- application/apps/rustcore/ts-bindings/src/native/native.jobs.ts
Fix of possible race condition, due call of job::abort() on TS side may be after job already finished on RS side.
> Fixing race condition on job cancel

- application/apps/indexer/session/src/handlers/export_raw.rs
- application/apps/indexer/session/src/state/observed.rs
- Creates suitable source for exporting as raw
- Allows export SomeIp into binary from PcapNg
- Fixes issue with exporting DLT from PcapNg
> Consider file type with export as raw (close #1867)

- application/apps/rustcore/ts-bindings/spec/session.errors.spec.ts
- application/apps/rustcore/ts-bindings/spec/session.exporting.spec.ts
- application/apps/rustcore/ts-bindings/spec/session.extract.spec.ts
- application/apps/rustcore/ts-bindings/spec/session.map.spec.ts
- application/apps/rustcore/ts-bindings/spec/session.search.spec.ts
- application/apps/rustcore/ts-bindings/spec/session.values.spec.ts
- Use right event to trigger next actions after observe opearation
> Fix jasmine tests

- application/apps/indexer/processor/src/export/mod.rs
- application/apps/precompiled/updater/src/env/args.rs
- application/client/package.json
- application/holder/package.json
- changelog.md
- Fix calling recent commands
- Fix context menu in concat view
- Fix files list in concat view
> Up to 3.10.6

- application/apps/rustcore/rs-bindings/src/js/session/mod.rs
- application/apps/rustcore/ts-bindings/src/api/session.ts
- application/apps/rustcore/ts-bindings/src/native/native.session.ts
- application/client/package.json
- application/client/src/app/service/session/dependencies/exporter.ts
- application/client/src/app/ui/elements/scrollarea/row/component.ts
- application/holder/package.json
- application/holder/src/service/bridge.ts
- application/holder/src/service/bridge/file/exportsession.ts
- application/holder/src/service/bridge/file/index.ts
- application/platform/ipc/request/file/exportsession.ts
- application/platform/ipc/request/file/index.ts
- changelog.md
- Change a way of file nature checking (text/binary)
- Added "Export All" to main output context menu
> Up to 3.10.7

- application/client/package.json
- application/client/src/app/service/session/dependencies/observing/operation.ts
- application/holder/package.json
- changelog.md
- Change closed chunk char for sending into serialport
> Up to 3.10.8

- application/client/package.json
- application/client/src/app/service/session/dependencies/teamwork.ts
- application/client/src/app/ui/views/sidebar/teamwork/component.ts
- application/client/src/app/ui/views/sidebar/teamwork/template.html
- application/holder/package.json
- application/holder/src/service/github.ts
- application/holder/src/service/github/requests/createcommit.ts
- application/holder/src/service/github/requests/createtree.ts
- application/holder/src/service/github/requests/getbranchsha.ts
- application/holder/src/service/github/requests/getcommit.ts
- application/holder/src/service/github/requests/getcommitbyfile.ts
- application/holder/src/service/github/requests/getfilecontent.ts
- application/holder/src/service/github/requests/getusername.ts
- application/holder/src/service/github/requests/updateref.ts
- application/platform/ipc/event/github/conflict.ts
- application/platform/ipc/event/github/index.ts
- application/platform/ipc/request/github/addrepo.ts
- application/platform/ipc/request/github/updaterepo.ts
- application/platform/types/github/index.ts
- changelog.md
- Allow custom entry-point for teamwork
- Fix loading metadata for teamwork for new files
- Suggest action on merge conflicts (teamwork)
> Up to 3.11.2

- application/apps/rustcore/ts-bindings/src/provider/provider.ts
- application/client/package.json
- application/client/src/app/service/history/collections.ts
- application/client/src/app/service/history/suitable.ts
- application/client/src/app/service/hotkeys.ts
- application/client/src/app/ui/styles/buttons.less
- application/client/src/app/ui/views/toolbar/history/preset/component.ts
- application/client/src/app/ui/views/toolbar/history/preset/styles.less
- application/client/src/app/ui/views/toolbar/history/preset/template.html
- application/holder/package.json
- application/holder/src/env/fs/accessor.ts
- application/platform/env/queue.ts
- changelog.md
- Optimization for "History/Presets" tab
> Up to 3.12.2

- application/client/package.json
- application/client/src/app/service/bridge.ts
- application/client/src/app/service/history/collections.ts
- application/client/src/app/service/history/storage.collections.ts
- application/client/src/app/service/session/dependencies/search/charts/store.update.ts
- application/client/src/app/service/session/dependencies/search/filters/store.update.ts
- application/client/src/app/service/session/dependencies/search/store.ts
- application/client/src/app/service/session/dependencies/search/store.update.ts
- application/client/src/app/ui/views/sidebar/search/filters/provider.ts
- application/holder/package.json
- application/holder/src/service/storage.ts
- application/platform/ipc/request/storage/entries.get.ts
- application/platform/ipc/request/storage/entries.set.ts
- changelog.md
- Optimization of the events life cycle of filters/charts/disabled
> Up to 3.12.3

- application/client/package.json
- application/client/src/app/service/history/collections.ts
- application/holder/package.json
- changelog.md
- Fix parsing disabled entities (filters/charts)
> Up to 3.12.4

- application/client/package.json
- application/holder/package.json
- changelog.md
> Up to 3.12.5

- application/apps/rustcore/ts-bindings/package.json
- application/apps/rustcore/ts-bindings/yarn.lock
- application/holder/package.json
- application/holder/yarn.lock
> Bump electron to 30.0.6

- application/client/package.json
- application/client/src/app/service/bridge.ts
- application/client/src/app/service/session.ts
- application/client/src/app/ui/elements/tree/component.ts
- application/holder/package.json
- application/holder/src/env/logs/index.ts
- application/holder/src/service/bridge.ts
- application/holder/src/service/electron/dialogs.ts
- application/holder/src/service/storage.ts
- application/holder/src/service/storage/entries.ts
- application/holder/src/service/unbound.ts
- application/holder/src/service/unbound/file/index.ts
- application/holder/src/service/unbound/file/isbinary.ts
- application/platform/ipc/request/file/index.ts
- application/platform/ipc/request/file/isbinary.ts
- application/platform/log/logger.ts
- application/platform/log/utils.ts
- changelog.md
- Allow open files from favorites by dblclick
- Fix the import/export presets feature
- Fix logger. Make it react to envvars correctly
- Upgrade electron version
> Up to 3.12.7

- application/apps/rustcore/wasm-bindings/Cargo.lock
- application/apps/rustcore/wasm-bindings/Cargo.toml
- application/apps/rustcore/wasm-bindings/spec/matcher.spec.ts
- application/apps/rustcore/wasm-bindings/src/matcher.rs
- application/client/package.json
- application/client/src/app/module/matcher/matchee.ts
- application/holder/package.json
- changelog.md
- Fix issue with non-UTF8 symbols in paths (recent actions)
> Up to 3.12.9

- cli/src/target/wrapper.rs
This PR provides the following hot fixes to the build CLI tool for the Wrapper target:
* Fix target in job definition for wrapper.
* Clean tests build directory and build it on each test run
> Build CLI: Clean Build for Wrapper Tests & Fix

- application/client/src/app/service/actions.ts
- application/client/src/app/service/actions/index.ts
- application/client/src/app/service/actions/jumpto.ts
- application/client/src/app/service/hotkeys.ts
- application/client/src/app/service/session/dependencies/cursor.ts
- application/client/src/app/ui/layout/component.ts
- application/client/src/app/ui/layout/popups/component.ts
- application/client/src/app/ui/layout/popups/styles.less
- application/client/src/app/ui/layout/styles.less
- application/client/src/app/ui/service/popup.ts
- application/client/src/app/ui/service/popup/popup.ts
- application/client/src/app/ui/views/dialogs/jumpto/component.ts
- application/client/src/app/ui/views/dialogs/jumpto/module.ts
- application/client/src/app/ui/views/dialogs/jumpto/styles.less
- application/client/src/app/ui/views/dialogs/jumpto/template.html
- application/client/src/app/ui/views/dialogs/module.ts
- application/client/src/app/ui/views/toolbar/details/component.ts
- application/client/src/app/ui/views/workspace/backing.ts
- application/holder/src/service/actions/index.ts
- application/holder/src/service/actions/jumpto.ts
- application/holder/src/service/menu.ts
- application/platform/ipc/request/actions/index.ts
- application/platform/ipc/request/actions/jumpto.ts
- application/platform/types/hotkeys/map.ts
> Add support of feature JumpToRow

- application/apps/rustcore/ts-bindings/src/api/executors/session.stream.nearest.executor.ts
- application/client/src/app/ui/elements/scrollarea/component.ts
- application/client/src/app/ui/elements/scrollarea/controllers/selection.ts
- application/client/src/app/ui/elements/scrollarea/row/component.ts
- application/client/src/app/ui/views/toolbar/search/results/component.ts
- application/platform/types/hotkeys/map.ts
- prevent requests to the nearest position (search results) on empty results
- remove "Copy As Formatted Table"
- apply formatted coping as soon as render is columns
> Improved selection

- application/apps/indexer/parsers/src/someip.rs
This PR improves the performance of SOME/IP DLT network-trace parsing by using dynamic caches for:
- Fallback Service-Version lookup
- Generated SOME/IP payload types
The resulting performance improvement is about 100%
> Use dynamic caching for SOME/IP DLT network-trace parsing

- application/apps/indexer/parsers/src/someip.rs
- application/apps/rustcore/ts-bindings/spec/session.observe.spec.ts
- application/client/.eslintrc.json
- application/client/src/app/ui/views/toolbar/details/component.ts
- application/client/src/app/ui/views/toolbar/details/styles.less
- application/client/src/app/ui/views/toolbar/details/template.html
This PR allows SOME/IP payloads to be rendered with pretty format in details view.
> Support pretty format in details view

- application/client/package.json
- application/client/src/app/service/bridge.ts
- application/client/src/app/service/session/dependencies/exporter.ts
- application/client/src/app/service/session/dependencies/stream.ts
- application/client/src/app/ui/elements/scrollarea/row/component.ts
- application/client/src/app/ui/views/sidebar/attachments/component.ts
- application/client/src/app/ui/views/sidebar/attachments/preview/component.ts
- application/client/src/app/ui/views/sidebar/search/providers/providers.ts
- application/client/src/app/ui/views/toolbar/history/state.ts
- application/holder/package.json
- application/holder/src/service/bridge/file/save.ts
- application/holder/src/service/electron/dialogs.ts
- application/platform/ipc/request/file/save.ts
- application/platform/types/files.ts
- changelog.md
- allow select columns, which will be exported into a file on search results export
- suggest default file name on exporting and saving of attachments
> Up to 3.14.1

- application/apps/indexer/Cargo.lock
- application/apps/indexer/parsers/src/someip.rs
- application/apps/indexer/sources/src/command/process.rs
- application/apps/rustcore/rs-bindings/Cargo.lock
This PR will change the SOME/IP parser to run in non-strict mode while parsing SOME/IP payloads.
Depends on: https://github.com/esrlabs/someip-payload/pull/10
> Parse someip payloads in non-strict mode.

- application/apps/indexer/stypes/generate.sh
This PR adds script to generate type script types from rust ones with description about how to include them in the system with notes to ensure the existing types won't be overwriting unintentionally.
> Protocol: Add script to generate types with description.

- application/client/package.json
- application/holder/package.json
- changelog.md
- Add support for nested search in the search results
- Upgrade Angular version to 19.x
- Upgrade Electron version to 34.x
- Upgrade the rest npm packages to recent versions
> Up to 3.15.0

- application/client/package.json
- application/client/src/app/schema/content/row.ts
- application/client/src/app/service/session/dependencies/cursor.ts
- application/client/src/app/service/session/dependencies/indexed.ts
- application/client/src/app/service/session/dependencies/search/highlights.ts
- application/client/src/app/service/session/dependencies/search/state.ts
- application/client/src/app/ui/elements/scrollarea/component.ts
- application/client/src/app/ui/elements/scrollarea/controllers/frame.ts
- application/client/src/app/ui/elements/scrollarea/controllers/service.ts
- application/client/src/app/ui/elements/scrollarea/row/component.ts
- application/client/src/app/ui/elements/scrollarea/row/standard/component.ts
- application/client/src/app/ui/views/toolbar/details/component.ts
- application/client/src/app/ui/views/toolbar/search/component.ts
- application/client/src/app/ui/views/toolbar/search/results/backing.ts
- application/client/src/app/ui/views/toolbar/search/results/component.ts
- application/client/src/app/ui/views/workspace/backing.ts
- application/holder/package.json
- changelog.md
- Fixed an issue related to breadcrumbs
- Fixed an issue with updating rows in views
> Up to 3.15.1

- application/client/package.json
- application/client/src/app/schema/content/row.ts
- application/client/src/app/ui/elements/scrollarea/row/component.ts
- application/client/src/app/ui/elements/scrollarea/row/standard/component.ts
- application/holder/package.json
- changelog.md
- Fixed an issue related to hashing row's state
> Up to 3.15.2

- application/client/package.json
- application/client/src/app/service/session/dependencies/search/state.ts
- application/client/src/app/ui/elements/scrollarea/controllers/frame.ts
- application/client/src/app/ui/views/toolbar/search/nested/component.ts
- application/client/src/app/ui/views/toolbar/search/results/component.ts
- application/holder/package.json
- changelog.md
- Fixed an issue related to navigation in a nested search
- Fixed an issue related to navigation in a major search
- Bind "Enter" with the next result in a nested search
> Up to 3.15.3

- application/client/package.json
- application/client/src/app/service/actions.ts
- application/client/src/app/service/actions/export.session.state.ts
- application/client/src/app/service/actions/import.session.state.ts
- application/client/src/app/service/actions/index.ts
- application/client/src/app/service/bridge.ts
- application/client/src/app/service/session/session.ts
- application/holder/package.json
- application/holder/src/service/actions/export.session.state.ts
- application/holder/src/service/actions/import.session.state.ts
- application/holder/src/service/actions/index.ts
- application/holder/src/service/bridge.ts
- application/holder/src/service/bridge/file/index.ts
- application/holder/src/service/bridge/file/write.ts
- application/holder/src/service/electron/dialogs.ts
- application/holder/src/service/menu.ts
- application/platform/ipc/request/actions/export.session.state.ts
- application/platform/ipc/request/actions/import.session.state.ts
- application/platform/ipc/request/actions/index.ts
- application/platform/ipc/request/file/index.ts
- application/platform/ipc/request/file/write.ts
- changelog.md
- Allows saving session state into a file (state includes: filters, charts, and disabled entities)
- Allow import filters, charts, and disabled entities from a file into the current session.
> Adds session state import & export

- application/client/src/app/service/bridge.ts
- application/client/src/app/service/plugins.ts
- application/client/src/app/ui/tabs/plugins/component.ts
- application/client/src/app/ui/tabs/plugins/desc.ts
- application/client/src/app/ui/tabs/plugins/details/component.ts
- application/client/src/app/ui/tabs/plugins/details/styles.less
- application/client/src/app/ui/tabs/plugins/details/template.html
- application/client/src/app/ui/tabs/plugins/list/component.ts
- application/client/src/app/ui/tabs/plugins/list/styles.less
- application/client/src/app/ui/tabs/plugins/list/template.html
- application/client/src/app/ui/tabs/plugins/module.ts
- application/client/src/app/ui/tabs/plugins/plugin/component.ts
- application/client/src/app/ui/tabs/plugins/plugin/styles.less
- application/client/src/app/ui/tabs/plugins/plugin/template.html
- application/client/src/app/ui/tabs/plugins/provider.ts
- application/client/src/app/ui/tabs/plugins/styles.less
- application/client/src/app/ui/tabs/plugins/template.html
- application/platform/types/files.ts
- Added basic view for Plugins Manager
> Basic view for PluginManager

- application/apps/indexer/session/src/state/observed.rs
- application/client/src/app/schema/render/tools.ts
- application/client/src/app/service/plugins.ts
- application/client/src/app/ui/tabs/observe/config-schema/component.ts
- application/client/src/app/ui/tabs/observe/origin/concat/component.ts
- application/client/src/app/ui/tabs/observe/origin/concat/template.html
- application/client/src/app/ui/tabs/observe/origin/file/component.ts
- application/client/src/app/ui/tabs/observe/origin/file/template.html
- application/client/src/app/ui/tabs/observe/origin/stream/component.ts
- application/client/src/app/ui/tabs/observe/origin/stream/template.html
- application/client/src/app/ui/tabs/observe/parsers/general/component.ts
- application/client/src/app/ui/tabs/observe/parsers/general/plugin/component.ts
- application/client/src/app/ui/tabs/observe/parsers/general/plugin/state.ts
- application/client/src/app/ui/tabs/observe/parsers/general/plugin/template.html
- application/client/src/app/ui/tabs/observe/parsers/general/template.html
- application/client/src/app/ui/tabs/observe/state.ts
- application/client/src/app/ui/tabs/plugins/provider.ts
- application/platform/types/observe/parser/index.ts
- Update observe view to make it for friendly for users. Actually, it removes a nested list of plugins and includes it into the main list of parsers.
> Update observe related view

- plugins/README.md
- plugins/templates/.gitignore
- plugins/templates/parser_template/.gitignore
- plugins/templates/parser_template/Cargo.toml
- plugins/templates/parser_template/README.md
- plugins/templates/parser_template/metadata.toml
- plugins/templates/parser_template/src/lib.rs
This PR solves basic requirements for #2220.   
It contains:
* Provide template for parser plugin to be start point for development.
* Extend README with parser template and plugins markdown files.
> Plugins: Parser Template & Update README

- application/client/src/app/service/recent/action.ts
- application/client/src/app/ui/tabs/observe/state.ts
- application/client/src/app/ui/tabs/plugins/template.html
- application/holder/src/service/menu.ts
- application/platform/types/observe/origin/plugin.ts
- application/platform/types/observe/parser/plugin/index.ts
- Resolve almost all "TODOs". Some of them shifted to "Step 2" as soon as it's a part of it
- Reorder application menu: move `Plugins Manager` to `Chipmunk` menu, remove calls of "File with plugin" and "Stream with plugin"; move "Folder with plugin" into `Chipmunk/Developing/Experimental`
- Disable "Add" button in Plugins Manager
> Small updates

- application/client/package.json
- application/client/src/app/ui/tabs/observe/parsers/extra/dlt/state.ts
- application/holder/package.json
- changelog.md
- Fix DLT file / source reading
- Fix DLT filtering
> Up to 3.16.3

- application/apps/indexer/processor/src/grabber/mod.rs
- application/apps/indexer/processor/src/text_source.rs
- application/apps/indexer/session/src/state/session_file.rs
- application/client/src/app/ui/env/entities/range.limited.ts
- application/client/src/app/ui/views/toolbar/search/results/backing.ts
- application/client/src/app/ui/views/workspace/backing.ts
> Fix sticky scrolling issue

- application/client/src/app/ui/tabs/plugins/details/component.ts
- application/client/src/app/ui/tabs/plugins/details/styles.less
- application/client/src/app/ui/tabs/plugins/details/template.html
- application/client/src/app/ui/tabs/plugins/provider.ts
- application/client/src/app/ui/tabs/plugins/template.html
- Fix for plugin's log rendering
- Show number of error/warning logs messages if exists
- Add placeholders for some cases
> Fix issue with plugin's log updating

- contribution.md
- developing/scripts/check.sh
- developing/scripts/install.sh
This PR close #2300.
It provides:
* Replace all ruby commands with commands from development CLI tool in Contribution page.
* Improve texts for contribution page as well.
* Update development scripts removing ruby parts from it.
> Update Contribution Page & Fix development scripts

- application/apps/indexer/Cargo.toml
This PR depends on: https://github.com/esrlabs/dlt-core/pull/49
> Update dlt-core to 0.20.1

- README.md
Small PR - Commit 84bab22843737f4caf9f3d50945a77b9a6da98b5 moved assets. This PR adjusts sources to changes.
> Fix broken assets

- .github/workflows/pullrequest_check.yml
- application/apps/indexer/definitions/src/parser.rs
- application/apps/indexer/definitions/src/record.rs
- application/apps/indexer/parsers/src/dlt/mod.rs
- application/apps/indexer/parsers/src/dlt/raw/mod.rs
- application/apps/indexer/parsers/src/lib.rs
- application/apps/indexer/parsers/src/someip/mod.rs
- application/apps/indexer/parsers/src/text/mod.rs
- application/apps/indexer/plugins_host/src/parser_shared/mod.rs
- application/apps/indexer/plugins_host/src/v0_1_0/parser/bindings.rs
- application/apps/indexer/plugins_host/src/v0_1_0/parser/mod.rs
- application/apps/indexer/processor/src/producer/mod.rs
- application/apps/indexer/session/src/handlers/observe/export_raw.rs
- application/apps/indexer/session/src/handlers/observe/mod.rs
- application/apps/indexer/session/src/handlers/observe/session.rs
This PR provides the following:
* Provide new parser definitions taken from the current master solution but with dynamic dispatch.
* Change method on Writer to `append()` which intended to append message to the internal memory of the writer without writing it to the underline target. This made this method sync and infallible 
* Optimize writer performance by reusing memory
* Remove redundant LogMesages enums: `Cow` already covers `String` and `&str` cases
* Refactoring by removing nested function.
* Performance improved by about 8-10% percent
* Improve error handling in producer loop.
* Remove internal buffer from producer.
* Skip CI checks for PRs not targeting master branch
> Components: Parser definitions + Plugins + Producer and Writer Optimizations

- application/client/src/app/ui/views/sidebar/attachments/preview/image/component.ts
- application/client/src/app/ui/views/sidebar/attachments/preview/text/component.ts
- application/holder/src/service/electron/protocol.ts
- resolve issue with rendering attachments on windows
> Resolving issue with attachments on windows
