application/client.plugins.standalone/parsers.messageframes/src/parser.ts
There was a left-over debugger-command in getParserName() of the message-frame plugin, which would automatically launch the debugger, whenever the conext-menu on a selection is triggered.
=> Remove debugger-command in message-frame parser

application/client.plugins.standalone/row.parser.ascii/package.json, application/client.plugins.standalone/row.parser.ascii/src/parser.ts, application/sandbox/row.parser.ascii/render/package.json
This will fix the display of colors encoded as ANSI escape-sequence.
It can also be made aware of custom styles in the row and thus only strip the escape-sequence.
=> Fix display of ANSI-colors

application/client.plugins/projects/processes/src/lib/views/sidebar.vertical/component.ts, application/sandbox/processes/process/package.json, application/sandbox/processes/process/src/process.env.ts, application/sandbox/processes/process/src/service.streams.ts
The processes-plugin will now first search for the default shell to execute and then correctly detect the environment-variables for the current user.
The home-directory will now be used as starting position.
=> Rework processes-plugin

application/client.plugins/projects/serial/src/lib/common/host.events.ts, application/client.plugins/projects/serial/src/lib/services/service.ts, application/client.plugins/projects/serial/src/lib/views/dialog/components.ts, application/client.plugins/projects/serial/src/lib/views/dialog/port.available/components.ts, application/client.plugins/projects/serial/src/lib/views/dialog/port.available/styles.less, application/client.plugins/projects/serial/src/lib/views/dialog/template.html, application/client.plugins/projects/serial/src/lib/views/dialog/titlebar/template.html, application/client.plugins/projects/serial/src/lib/views/sidebar.vertical/component.ts, application/sandbox/serial/process/package.json, application/sandbox/serial/process/src/consts/commands.ts, application/sandbox/serial/process/src/services/service.sessions.ts
Popup window show recently connected ports (via config file saved on user PC)
- directly connect to port
- remove individual port
- remove all ports
Notification on error/warning (serial plugin)
- show error as notfication and log it
=> Manage recently connected ports

application/client.core/src/app/environment/components/dialogs/multiplefiles/component.ts, application/client.core/src/app/environment/components/dialogs/multiplefiles/template.html, application/client.core/src/app/environment/services/service.file.opener.ts
New feature:
- When drag&dropping multiple files into Chipmunk the user can right-click to call context menu
- In the context menu, the user can "select all", "deselect all" or "reverse select all" files
Fix:
- When no file is checked in the popup window, clicking "merge" or "concat" will just close the popup window
=> #822 Multiple files dialog

application/client.core/src/app/environment/components/views/search/component.ts
When using keyboard shortcuts to save filter/chart in search, the request is being searched for twice due to some "bad" implementation.
=> Resolve saving issue filters/charts

CHANGELOG.md, application/electron/package.json
- Filtering processes list on ADB
- Fixed MacOS issue for Shell Extention
=> Up to 2.21.0

application/apps/indexer/session/src/handlers/observe.rs, application/apps/indexer/session/src/state/api.rs, application/apps/indexer/session/src/state/mod.rs, application/apps/indexer/session/src/state/session_file.rs, application/client/src/app/service/session/dependencies/observing/implementations/files.ts, application/client/src/app/ui/tabs/multiplefiles/styles.less, application/client/src/app/ui/views/sidebar/attachments/template.html
- Allows attaching to same session text & binary files after concat operation was done
- Fires error on attempt to attach a file to session with linked session file
=> Fix attaching files after concat (close #1866)

application/client/src/app/service/history.ts, application/client/src/app/service/history/provider.ts, application/client/src/app/ui/views/sidebar/search/component.ts, application/client/src/app/ui/views/sidebar/search/providers/providers.ts
Add ability to import and export all filters, Charts from sidebar. At the moment user can still export all filters from history in toolbar but to enhance the accessibility this PR add same feature in sidebar.
Fixes: #1833
=> Add import-export options for sidebar filters

application/holder/hooks/afterSign.js
Neccessary since Apple will deprecate the old way
(to notarize your macOS software with Apple)
=> Use new notarytool command-line utility

.gitignore, application/apps/rustcore/ts-bindings/package.json, application/apps/webassembly/ansi/package.json, application/apps/webassembly/matcher/package.json, application/apps/webassembly/utils/package.json, application/client/package.json, application/client/src/app/schema/render/columns.ts, application/client/src/app/ui/env/entities/value.limited.ts, application/client/src/app/ui/tabs/observe/parsers/extra/dlt/state.ts, application/holder/package.json, application/platform/env/str.ts, application/platform/package.json, application/platform/types/observe/origin/concat.ts, application/platform/types/observe/origin/file.ts, changelog.md
- Fix the path's parser (windows)
- Fix the default column's sizer
- Fix DLT statistic collector
=> Up to 3.9.12

contribution.md
This PR closes #1959 
It updates the documentation for the contribution documentations with the current implementation for ruby rake task (As I understood the code)
- CLI commands and their description has been updated for build, run and changes in frontend showing the two different configurations (develop and production) and defaulting to develop
- Outdated build instructions for the backend has been deleted and replaced with the recommended command for rebuild and run (Maybe I missed something in the code but I assumed that for backend build we can always use `rake run_dev`)
- Linting commands has been updated
This PR is related to #1960
=> Update contribution documentation

application/client/package.json, application/client/src/app/service/session/dependencies/teamwork.ts, application/holder/package.json, application/holder/src/service/github.ts, changelog.md
- Fix create/update/change repo issue in context of Teamwork feature
=> Up to 3.11.1

application/apps/indexer/Cargo.lock, application/apps/indexer/sources/src/command/process.rs
By some reason after recent updates (crates and probably linux), from time to time after the test spawned process stays alive; as a result, we are stuck without a resolved test.
Probably makes sense to make a deeper investigation of such behavior.
=> Fix spawning process test

application/apps/indexer/session/src/handlers/observing/mod.rs, application/apps/precompiled/updater/src/env/args.rs
This PR makes sure that cancel call will be invoked on the cancellation token instance if running producer returns with an operation error to avoid having the app stuck in `join!()` calls since some tasks like `tail::track()` won't return until cancel is called.
For Example the current Implementation won't show any error message in `indexer_cli` tool if `run_source()` call returns an error because it will be waiting for `tail::track()` to finish, which won't finish in that case until the user closes the session manually, and then at that point the error message will be printed.
=> Sessions: Cancel other tasks on operation errors

application/apps/indexer/Cargo.toml, application/apps/indexer/addons/dlt-tools/Cargo.toml, application/apps/indexer/addons/text_grep/Cargo.toml, application/apps/indexer/indexer_base/Cargo.toml, application/apps/indexer/indexer_cli/Cargo.toml, application/apps/indexer/merging/Cargo.toml, application/apps/indexer/parsers/Cargo.toml, application/apps/indexer/processor/Cargo.toml, application/apps/indexer/session/Cargo.toml, application/apps/indexer/sources/Cargo.toml
Cargo provides the feature [workspace.dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) to manage shared dependencies among all libraries sharing the same workspace.
Using this feature I've gathered all shared dependencies with the same major version in `Cargo.toml` file in the `indexer` directory and replaced the specified version for dependencies in all its child-libs.
This refactoring shouldn't change the current dependencies tree because there is no changes in any of `Cargo.lock` files
=> Group shared dependencies with 'workspace.dependencies' 

.github/workflows/release_testing.yml
This PR activates the commented-out distribution part of the release.
Now that we've tested the release on our machines successfully, we need to test if it works with the distributions before we replace the current Ruby release with the new Build CLI tool one
=> Build CLI: Activate distribution on test release

application/apps/indexer/processor/src/text_source.rs, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/README.md, cli/integration_tests/release.py, cli/integration_tests/run_all.py, cli/src/cli_args.rs, cli/src/job_type.rs, cli/src/jobs_runner/jobs_state.rs, cli/src/jobs_runner/mod.rs, cli/src/main.rs, cli/src/target/mod.rs
This PR resolves a clippy warning by using `lines()` instead of `split()` with pattern
=> Build CLI: More Fixes & Improvements

cli/Cargo.lock, cli/Cargo.toml
This PR closes #2089 
Build CLI tool uses `git2` crate to determine Chipmunk root directory only, and for that basic functionality, it doesn't need of the default features on that crate.
Remove the default features also removed the dependency on `openssl` while keeping finding Chipmunk root functionality working as before.
=> Build CLI Tool: Remove 'openssl` external dependency  

application/apps/indexer/Cargo.lock, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/src/binary/pcap/legacy.rs, application/apps/indexer/sources/src/binary/pcap/ng.rs, application/apps/indexer/sources/src/binary/raw.rs, application/apps/indexer/sources/src/command/process.rs, application/apps/indexer/sources/src/lib.rs, application/apps/indexer/sources/src/serial/serialport.rs, application/apps/indexer/sources/src/socket/tcp.rs, application/apps/indexer/sources/src/socket/udp.rs, application/apps/rustcore/rs-bindings/Cargo.lock
This PR replaces the macro `async-trait` for `ByteSource` trait with rust native support for async functions in traits, avoiding the extra heap allocation on the return value that was enforce by the `async-trait` macro.
The warning about async in public traits is suppressed since we are using the trait in our own codebase only.
I've made simple benchmarks on a DLT file with the size 409M and got a slightly better performance:
```md
**Results in Mili-seconds**
File Read Took: 8182
File Read Took: 8113
File Read Took: 8225
File Read Took: 7996
** Avg: 8129 MS **
-----------------------------------------------------
File Read Took: 8395
File Read Took: 8258
File Read Took: 8252
File Read Took: 8291
** Avg: 8299 MS ** 
```
=> Replace async-trait crate with Rust native support

application/apps/indexer/Cargo.lock, application/apps/indexer/Cargo.toml, application/apps/indexer/processor/Cargo.toml, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/benches/mocks/mock_parser.rs, application/apps/indexer/sources/benches/mocks/mock_source.rs, application/apps/indexer/sources/benches/mocks/mod.rs, application/apps/indexer/sources/benches/producer_benchmarks.rs, application/apps/indexer/sources/src/lib.rs
This PR provides a new benchmark for the producer loop with mock structs for `Parser` and `ByteSource`.
This point from this benchmark to have a solid comparison for the producer loop only without the noise of the parsers and the byte sources and all their IO operations. 
However, the noise of the async runtime is noticeable here since the producer loop with mocks parser and byte-source is simple and doesn't have a lot of logic in it, which made the overhead from the runtime unfortunately noticeable.
I've tried to reduce the noise from async runtime as possible by configuring the benchmark and implementing some tricks on the mocks to avoid calling `Future::poll()` on their methods by using and inlining inner functions.
Those changes made the benchmarks fairly stable (Changes normally …
=> Benchmark for Producer loop

application/client/package.json, application/holder/package.json, changelog.md
- prevent requests to the nearest position (search results) on empty results
- remove "Copy As Formatted Table"
- apply formatted coping as soon as the render is columns
- add support Some/IP messages from DLT payload
- switching build workflow from ruby scripts (rake) to own build CLI module
- add benchmark tests to keep control of performance
=> Up to 3.13.0

application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/benches/bench_utls.rs, application/apps/indexer/sources/benches/dlt_producer.rs, application/apps/indexer/sources/benches/mocks_benchmarks.rs, application/apps/indexer/sources/benches/mocks_producer.rs, application/apps/indexer/sources/benches/someip_legacy_producer.rs, application/apps/indexer/sources/benches/someip_producer.rs, application/apps/indexer/sources/benches/text_producer.rs, application/apps/indexer/sources/src/binary/pcap/legacy.rs, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/README.md, cli/config/bench_core.toml, cli/integration_tests/bench.py, cli/integration_tests/run_all.py, cli/src/benchmark/core.rs, cli/src/benchmark/mod.rs, cli/src/cli_args.rs, cli/src/dev_environment.rs, cli/src/location.rs, cli/src/main.rs
This PR can't be merged until #2102 is merged to avoid merge conflicts since both of them are increasing the version of the build CLI tool.
* This PR provide benchmarks for actual parser in Chipmunk in the producer loop, similar to the benchmark with mocking parsers introduced in #2088. These benchmarks accept their input source and additional configurations via environment variables and load them before start measuring to reduce any noise from IO operations.
* A new subcommand is introduced to the Build CLI to run the benchmarks directly with the option to provide the input source and additional configuration as cli arguments to avoid the complexity of using environment variables.
* The available benchmarks will be listed in a configuration file to avoid increasing the version of the CLI …
=> Benchmarks for actual Parsers & Build CLI Integrations  

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/src/cli_args.rs, cli/src/main.rs, cli/src/spawner.rs, cli/src/version.rs
This PR closes #2112 
* It adds a check to compare the version of the installed tool to the latest version of the build CLI tool on the user's local repository. This is pragmatic solution to avoid checking for the updates from master branch on GitHub on each run of the tool or develop more complex solution by checking for updates once daily and cache the value somewhere. 
Since the tool will be running inside Chipmunk repo anyway then it would make sense to check the available version on the local repo.
If this check fails, then a warning will be printed to the users, but the tool will continue executing.
* Logs are extended with each running command with the current directory where it's running
* This PR adds the version to the current output of the help command as well.
=> Build CLI: Check for newer version locally & Commands Info in Logs

application/apps/indexer/sources/benches/bench_utls.rs, application/apps/indexer/sources/benches/dlt_producer.rs, application/apps/indexer/sources/benches/mocks/mock_source.rs, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/src/benchmark/core.rs, cli/src/benchmark/mod.rs
This PR provides the following improvements and fixes to the build CIL tool and benchmarks:
* `Sample Size` can be configured via environment variables or with CLI arguments on build CLI tool.
* DLT parser option `with_storage_header` is set to true by default since this is the default case for DLT files (which is the only case for running benchmarks currently)
* Change confusing error message on mock byte source to more meaningful one.
=> Benchmarks & Build CLI Tool: Small Improvements & Fixes

application/apps/indexer/addons/dlt-tools/src/lib.rs, application/apps/indexer/indexer_cli/src/interactive.rs, application/apps/indexer/indexer_cli/src/main.rs, application/apps/indexer/parsers/src/dlt/mod.rs, application/apps/indexer/parsers/src/lib.rs, application/apps/indexer/parsers/src/someip.rs, application/apps/indexer/parsers/src/text.rs, application/apps/indexer/processor/src/export/mod.rs, application/apps/indexer/session/src/handlers/export_raw.rs, application/apps/indexer/session/src/handlers/observing/mod.rs, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/benches/bench_utls.rs, application/apps/indexer/sources/benches/mocks/mock_parser.rs, application/apps/indexer/sources/benches/mocks_multi_producer.rs, application/apps/indexer/sources/benches/mocks_once_producer.rs, application/apps/indexer/sources/src/producer.rs, application/apps/indexer/sources/src/producer/tests.rs, application/apps/indexer/sources/src/producer/tests/mock_parser.rs, application/apps/indexer/sources/src/producer/tests/mod.rs, application/apps/indexer/sources/src/producer/tests/multi_parse.rs, application/apps/indexer/sources/src/producer/tests/single_parse.rs, cli/config/bench_core.toml
This PR Changes the Producer Loop to support parsers returning multiple items at once on calling `parse()` method, which is essentially for implementing parsers in the plugins system.
Following has been implemented:
Here are some benchmarks from DLT file (541 MB) running in Chipmunk app and in dlt benches of the current master and this branch for comparison + Benchmarks with mock parser returning single item in master and `iter::once()` in this Branch:
```Markdown
File Read Took: 11.464 ms
File Read Took: 11.343 ms
File Read Took: 11.382 ms
dlt_producer            time:   [4.0264 s 4.0323 s 4.0381 s]
dlt_producer            time:   [4.0504 s 4.0603 s 4.0698 s]
mocks_producer/50000    time:   [5.0924 ms 5.1012 ms 5.1111 ms]
mocks_producer/50000    time:   [4.8922 ms 4.9009 ms 4.9105 ms] …
```
=> Core: Producer Loop with Multi Parse Result Items 

application/apps/indexer/session/src/state/attachments.rs, application/apps/indexer/session/src/state/mod.rs, application/client/package.json, application/holder/package.json, changelog.md
- sanitize the attachment path before saving
- prevent closing session on invalid attachment
- add support for multiple values/messages on the producer level
=> Up to 3.13.4

application/apps/indexer/processor/src/export/mod.rs
This PR fixes a Bug introduced in #2114 
Break statements are existing mistakenly the newly added nested loop now instead of exiting the outer `while let` loops. Which led to different export results compared to the previous implementation.
To fix this, this PR added labels to the outer loops then changed all the break statements to refer to the matching outer loops labels.
=> Fix export after multiple producer's return items

application/apps/indexer/sources/benches/dlt_producer.rs, application/apps/indexer/sources/benches/mocks/mock_parser.rs, application/apps/indexer/sources/benches/mocks/mock_source.rs, application/apps/indexer/sources/benches/mocks_multi_producer.rs, application/apps/indexer/sources/benches/mocks_once_producer.rs, application/apps/indexer/sources/benches/someip_legacy_producer.rs, application/apps/indexer/sources/benches/someip_producer.rs, application/apps/indexer/sources/benches/text_producer.rs
This PR:
* Replaces `black_box()` function from criterion with the one from the standard library `std::hint::black_box()` after stabilizing it.
* Replaces `bench_with_input()` function with manual black boxing since they are still using `criterion::black_box` function under the hood.
The function from criterion is already marked as deprecated in their master branch and will be using the one from the standard library in their next release as well.
=> Benchmarks: Replace Criterion `black_box` with the Standard Library Function

application/apps/indexer/Cargo.lock, application/apps/indexer/Cargo.toml, application/apps/indexer/parsers/src/dlt/mod.rs
This PR:
* Applies the default error mapping from DLT error into parser error on all DLT parsers after changes on the crate `dlt-core` in the PR https://github.com/esrlabs/dlt-core/pull/27.
* Change referencing `dlt-core` from GitHub link to the current version on `crates.io` after it has been updated there to the latest version too.
=> DLT: Error Mapping on Parsers & Reference Crate Published Version

application/apps/rustcore/rs-bindings/Cargo.lock
This update was missing in the last PR #2113 to update the reference on `dlt-core` crate
=> Update `cargo.lock` for rs-bindings with `dlt-core` Crate

.github/workflows/lint_master.yml, .github/workflows/pullrequest_check.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/README.md, cli/integration_tests/run_all.py, cli/integration_tests/user_config.py, cli/src/benchmark/core.rs, cli/src/cli_args.rs, cli/src/location.rs, cli/src/main.rs, cli/src/shell.rs, cli/src/spawner.rs, cli/src/tracker.rs, cli/src/user_config.rs
This PR closes #2119
This PR closes #2140
This PR closes #2141
It provides a way for the users to configure their environment and preferences in a file in Chipmunk home directory to be loaded and used by the build CLI tool
It Provides fixes improvements in fixes to run CI checks which are described in the linked issues.
The following configuration are provided currently:
* The Shell to run the processes on (Bash, Zsh, Fish...)
* Default UI preference to use with the tool (bars, report, print, immediate)
=> Build CLI: Configurations on User Level & CI Improvements

application/apps/indexer/Cargo.lock, application/apps/indexer/session/Cargo.toml, application/apps/indexer/session/src/state/mod.rs, application/apps/indexer/session/src/state/session_file.rs, application/apps/indexer/session/src/unbound/cleanup.rs, application/apps/indexer/session/src/unbound/mod.rs
This PR closes #2137 
It improves cleaning up the temporary files (Logs and attachments) generated by an observe session with the following changes:
* Cleanup function for individual sessions is called when the session is dropped instead of calling it explicitly, ensuring that it will be called even on panics or in integration tests.
* Extend cleanup function for individual sessions to remove the attachments besides removing the main log file.
* A general cleaning up function to scan the temporary directory in Chipmunk and remove all files and directories that are older than two months. This function will be called on start of Chipmunk and will run on a separate thread to avoid blocking the initialization of the app on cleaning up huge temporary directory
=> Core: Improve Cleanup Temporary Files in Chipmunk Home Directory 

application/client/package.json, application/holder/package.json, changelog.md
- better parsing Some/IP in the scope of DLT Network Trace
- cleanup temporary session files
=> Up to 3.14.2

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/src/release/codesign/macos.rs
This PR provides the following fixes and improvements to notarizing process while releasing to MacOS:
* Print logs before checking the status of the notarize command to ensure that logs will be shown on command errors.
* Hide credentials from output logs.
* Update tool version & Add changes to change log
=> Build CLI Release: Fix MacOS notarize logs

application/apps/indexer/Cargo.lock, application/apps/indexer/Cargo.toml, application/apps/indexer/processor/Cargo.toml, application/apps/indexer/processor/benches/map_benchmarks.rs, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/benches/dlt_producer.rs, application/apps/indexer/sources/benches/macros/mock_producer_multi.rs, application/apps/indexer/sources/benches/macros/mock_producer_once.rs, application/apps/indexer/sources/benches/macros/mod.rs, application/apps/indexer/sources/benches/mocks_multi_producer_jemalloc.rs, application/apps/indexer/sources/benches/mocks_multi_producer_sysalloc.rs, application/apps/indexer/sources/benches/mocks_once_producer.rs, application/apps/indexer/sources/benches/mocks_once_producer_jemalloc.rs, application/apps/indexer/sources/benches/mocks_once_producer_sysalloc.rs, application/apps/indexer/sources/benches/someip_legacy_producer.rs, application/apps/indexer/sources/benches/someip_producer.rs, application/apps/indexer/sources/benches/text_producer.rs, application/apps/rustcore/rs-bindings/Cargo.lock, application/apps/rustcore/rs-bindings/Cargo.toml, application/apps/rustcore/rs-bindings/src/lib.rs, cli/config/bench_core.toml
This PR closes #2117 
This PR changes the used memory allocator in Rust to [mimalloc](https://crates.io/crates/mimalloc) memory allocator because it's provided performance gain about 9% in the producer loop.
* The allocator is set in `rs-bindings` crates + in each existing benchmarks.
* I've extended the benchmarks with mock structs to one benchmark for each well-known memory allocator (standard system memory allocator, [~~jemalloc~~](https://docs.rs/jemallocator/latest/jemallocator/) and `mimalloc`).
* To achieve these extensions, I've created macros to generate the same benchmarks for the given memory allocator.
* Benchmarks have been extended in the Build CLI Tool configuration as well.
**Update:**
`jemalloc` allocator support on Windows is still unstable, which makes it unrelevant for …
=> Use `mimalloc` Memory Allocator & Extend Benchmarks with Different Memory Allocators 

application/apps/indexer/Cargo.lock, application/apps/indexer/Cargo.toml, application/apps/indexer/addons/someip-tools/Cargo.toml, application/apps/indexer/addons/someip-tools/src/lib.rs, application/apps/indexer/parsers/Cargo.toml, application/apps/indexer/parsers/src/dlt/fmt.rs, application/apps/indexer/parsers/src/someip.rs, application/apps/rustcore/ts-bindings/spec/session.observe.spec.ts
This PR will add information from the DLT network-trace prefix to the resulting SOME/IP information being displayed.
In DLT network-traces for SOME/IP the DLT payload contains of two arguments, where the first argument is a prefix with additional information on the actual SOME/IP message in the the second argument.
For the implementation the prefix will be expected to consist of:
- 4 bytes as IPv4 address
- 2 bytes as udp/tcp port
- 1 byte as protocol type (0 = local, 1 = tcp, 2 = udp)
- 1 byte as message direction (0 = incoming, 1 = outgoing)
- 1, 2 or 4 bytes as SOME/IP instance-id
=> Parse DLT network-trace prefix for SOME/IP messages

application/client/package.json, application/client/src/app/service/history/collections.ts, application/client/src/app/service/history/session.ts, application/client/src/app/service/history/storage.collections.ts, application/client/src/app/ui/views/toolbar/history/state.ts, application/holder/package.json, changelog.md
- show recently added filters after importing
- add parsing of DLT payload's network prefix
=> Up to 3.14.3

.github/workflows/benchmarks.yml, scripts/benchmarks/process.rb, scripts/benchmarks/setup_dev_tools.sh
This resolves the issue where self hosted runner did not get update the rust version and was locked on an older version of nj-cli(due to local dependencies on the self hosted runner).
=> Resolve rust version update issues with self hosted runner

cli/config/codesign_macos.toml
This PR sets the verbose level on `codesgin` command to 4
=> Build CLI Codesign MacOS: Increase verbose level

.github/workflows/benchmarks.yml, .github/workflows/lint_master.yml, .github/workflows/pullrequest_check.yml
This PR resolves the issue [GitHub Action: Rust-Cache action failing silently](https://github.com/esrlabs/chipmunk/issues/2153)
This also resolves the issue with benchmarks being triggered even when the prerequisite workflow failed.
=> Resolve issue with Rust-Cache action failing silently - PR

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/dir_checksum/Cargo.toml, cli/dir_checksum/tests/integration_tests.rs, cli/integration_tests/build.py, cli/src/build_state_records.rs, cli/src/jobs_runner/jobs_resolver.rs, cli/src/target/mod.rs, cli/src/version.rs
This PR provides the following changes to the build CLI tool:
* Removes Rust Core from the build dependencies to run the app, since it's not involved in build process, instead it'll be built form rs-bindings directly
* Keep track on the state of involved targets in last build only. Avoiding false positives in skipping builds when saved targets states belongs to different build runs.
* Added pretty assertion for unit tests in Build CLI tool
=> Build CLI: Remove Core from dependencies & Keep state on involved targets in last build only

application/apps/protocol/test.sh
This PR includes:
* Use build cli tool instead of rake to run protocol tests in ts-bindings.
* Update printing infos since we are running proptests as well.
=> Use build CLI to run protocol tests

application/client/package.json, application/holder/package.json, changelog.md
- Using binary format for messaging instead of JSON strings
=> Up to 3.14.4

application/apps/indexer/stypes/Cargo.toml
This PR sets optimization level of `proptest` crate and its dependencies to max to optimize the performance of prop-tests, according to [The tips and tricks section in proptest book](https://proptest-rs.github.io/proptest/proptest/tips-and-best-practices.html#setting-opt-level)
=> Max `proptest` optimizations to increase tests performance

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/dir_checksum/Cargo.toml, cli/integration_tests/build.py, cli/src/cli_args.rs, cli/src/job_type.rs, cli/src/jobs_runner/job_definition.rs, cli/src/jobs_runner/jobs_resolver.rs, cli/src/jobs_runner/mod.rs, cli/src/log_print.rs, cli/src/main.rs, cli/src/print_dot.rs, cli/src/release/env_utls.rs, cli/src/release/mod.rs, cli/src/spawner.rs, cli/src/target/mod.rs, cli/src/target/wasm.rs, cli/src/target/wrapper.rs, cli/src/tracker.rs, cli/src/version.rs
This PR provides various fixes and improvement to the build CLI tool:
* It lists only build related jobs as dependencies allowing lint and test jobs to run in parallel, avoiding blocking jobs until the lint or test jobs of their dependencies are done (as in the current solution) 
* Add rust core as dependency for protocol and rs-bindings to ensure they will be rebuilt on changes in rust core.
* Skip build, test, lint job if any of the build related jobs of their all dependencies failed.
* Build related jobs for linting and testing can be skipped if possible.
* Fix to avoid running test and lint jobs on the dependencies of a job since only build jobs are needed
* Stop release on any failing build jobs + Active fail fast on release.
* Skipped jobs should be marked in the TUI with and …
=> Build CLI: Fixes for resolving dependencies & Running jobs in parallel

application/apps/indexer/plugins_host/src/plugins_manager/load/mod.rs, application/client/src/app/service/actions/folder.plugins.ts, cli/chipmunk-cli/Cargo.lock, plugin_examples/README.md
This PR closes #2200 
It includes:
* File names for plugin binary and metadata files must match the directory name of the plugin, making the naming conventions clear for plugin developers.
* Update plugins README with the changes as well.
=> Plugins: Set constrains for plugin filenames.

application/apps/indexer/Cargo.lock, application/apps/indexer/Cargo.toml, application/apps/indexer/addons/bufread/Cargo.toml, application/apps/indexer/addons/bufread/README.md, application/apps/indexer/addons/bufread/benches/bench_config.rs, application/apps/indexer/addons/bufread/benches/buffer_benches.rs, application/apps/indexer/addons/bufread/benches/reader_benches.rs, application/apps/indexer/addons/bufread/src/lib.rs, application/apps/indexer/addons/bufread/tests/proto.rs, application/apps/indexer/addons/bufread/tests/proto_tests.rs, application/apps/indexer/addons/bufread/tests/reader_proptest.rs, application/apps/indexer/addons/text_grep/Cargo.toml, application/apps/indexer/addons/text_grep/src/buffer.rs, application/apps/indexer/addons/text_grep/src/lib.rs, application/apps/indexer/processor/Cargo.toml, application/apps/indexer/processor/src/search/buffer.rs, application/apps/indexer/processor/src/search/searchers/mod.rs, application/apps/indexer/processor/src/text_source.rs, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/src/binary/pcap/legacy.rs, application/apps/indexer/sources/src/binary/pcap/ng.rs, application/apps/indexer/sources/src/binary/raw.rs, application/apps/indexer/sources/src/command/process.rs, application/apps/indexer/sources/src/serial/serialport.rs, application/apps/indexer/sources/src/socket/tcp.rs, application/apps/indexer/sources/src/socket/udp.rs, application/apps/indexer/stypes/Cargo.toml, application/apps/protocol/Cargo.lock, application/apps/rustcore/rs-bindings/Cargo.lock
This PR removes the chipmunk dependencies to buf_redux.
=> Remove buf redux

cli/development-cli/CHANGELOG.md, cli/development-cli/Cargo.lock, cli/development-cli/Cargo.toml, cli/development-cli/src/build_state_records.rs, cli/development-cli/src/main.rs, cli/development-cli/src/target/mod.rs
This PR closes #2227 
It provides Removing record file entirely on the start of any clean job instead of trying to update the record file, making clean command more reliable because updating the record file may fail more often than removing it.
=> Development CLI: Remove targets record file on Clean.

application/apps/indexer/sources/src/socket/mod.rs, application/apps/indexer/sources/src/socket/tcp.rs, application/apps/indexer/sources/src/socket/udp.rs, cli/chipmunk-cli/Cargo.lock
This PR includes:
* Increase the capacity of the internal buffer in socket byte sources to 1MB instead of the default value 8KB.
* Add Checks for socket byte source to avoid filling the internal buffer if the server is sending the data with high frequency because the producer loop will call load on each iteration while some parsers will parse one item only on each iteration.
* Call flush on consume when there is not enough writable memory.
* Another check if the buffer is filled and return an error if we can't add all the incoming bytes into the buffer.
=> Socket sources: Improvements for internal buffers

application/apps/indexer/addons/bufread/src/lib.rs, application/apps/indexer/addons/bufread/tests/buffer_probtest.rs, application/apps/indexer/addons/bufread/tests/reader_proptest.rs
This PR will add a proptest for the DeqBuffer with random API calls, plus a fix for ensuring the start/end offset integrity within the buffer on possible overflowing read acknowledges.
=> Add proptest for DeqBuffer

application/apps/indexer/plugins_host/src/plugins_manager/load/mod.rs, application/apps/indexer/plugins_host/src/plugins_manager/tests.rs, application/apps/indexer/stypes/bindings/plugins.ts, application/apps/indexer/stypes/src/plugins/mod.rs, application/apps/indexer/stypes/src/plugins/proptest.rs, application/client/src/app/ui/tabs/plugins/component.ts, application/client/src/app/ui/tabs/plugins/desc.ts, application/client/src/app/ui/tabs/plugins/details/component.ts, application/client/src/app/ui/tabs/plugins/provider.ts, application/platform/types/bindings/plugins.ts, plugins/examples/dlt_parser/README.md
This PR closes #2247 
It provides the following:
* Provide the path of readme file from rust core instead from UI.
* Basic implementation for reload functionality on front end.
* Complete rename 'ts' to 'timestamp' in front end.
* Basic readme file for DLT parser plugin
=> Plugins: README from core & Reload in UI

plugins/README.md, plugins/plugins_api/README.md, plugins/plugins_api/src/lib.rs, plugins/plugins_api/src/shared/config.rs
This PR checks one task from #2222, providing documentation for `plugins_api` crate.
It includes:
* Provide README file for plugins_api crate and use it as the main page for `cargo docs`
* Small fixes to documentation comments in code, removing warning when `cargo doc` is run.
=> Plugins: Documentation for `plugins_api` crate

application/apps/indexer/Cargo.lock, application/apps/indexer/plugins_host/Cargo.toml, application/apps/indexer/plugins_host/benches/plugin_parser_init.rs, application/apps/indexer/plugins_host/src/parser_shared/plugin_parse_message.rs, application/apps/indexer/plugins_host/src/plugins_manager/load/paths.rs, application/apps/indexer/plugins_host/src/v0_1_0/bytesource/bytesource_plugin_state.rs, application/apps/indexer/plugins_host/src/v0_1_0/parser/parser_plugin_state.rs, application/apps/indexer/plugins_host/src/v0_1_0/shared/bindings.rs, application/apps/indexer/plugins_host/src/wasm_host/mod.rs, application/apps/indexer/session/src/handlers/observing/file.rs, application/apps/indexer/session/src/unbound/mod.rs, application/apps/indexer/sources/benches/plugin_praser_producer.rs, application/apps/indexer/stypes/src/plugins/mod.rs, application/apps/rustcore/rs-bindings/Cargo.lock, plugins/plugins_api/src/bytesource/mod.rs, plugins/plugins_api/src/parser/mod.rs
This PR closes #2248 
* It resolves the remaining TODOs in code regarding the prototyping stage.
* Resolves generating shared types after resolving the issue in `wasmtime`
* Updates `wasmtime` and `wasmtime-wasi` to the latest stable version 31
=> Plugins: Final Cleanups & Resolving TODOs before step 1

application/apps/indexer/Cargo.lock, application/apps/indexer/session/src/handlers/observing/stream.rs, application/apps/indexer/sources/Cargo.toml, application/apps/indexer/sources/src/socket/mod.rs, application/apps/indexer/sources/src/socket/tcp.rs, application/apps/indexer/sources/src/socket/tcp/reconnect.rs, application/apps/rustcore/rs-bindings/Cargo.lock, cli/chipmunk-cli/CHANGELOG.md, cli/chipmunk-cli/Cargo.lock, cli/chipmunk-cli/Cargo.toml, cli/chipmunk-cli/README.md, cli/chipmunk-cli/src/cli_args/mod.rs, cli/chipmunk-cli/src/session/mod.rs, cli/chipmunk-cli/src/session/socket.rs
This PR provide the following:
* Reimplement the reconnect function with cancel-safety in mind. The new implementation will spawn reconnecting in a new task keeping track on each progress.
* Possibility to configure `keepalive` on TCP source + CLI arguments for its configuration on Chipmunk CLI, keeping the implementation on Chipmunk GUI for later.
* Unit tests for reconnect and cancel-safe load and reconnect calls.
* Change duration units on Chipmunk CLI from milliseconds to units since seconds accuracy is more suitable for this domain.
* Increase Chipmunk CLI version + Update readme and changelog
**Note:**
Manual timeout checks aren't implemented here, because they would increase the code complexity and introducing `Arc<RwLock<>` wrappers around the tcp sockets even though that this …
=> TCP: Reconnect with Cancel-Safety & Use `keepalive` + Chipmunk CLI

application/apps/indexer/addons/dlt-tools/src/lib.rs, application/apps/indexer/indexer_cli/src/interactive.rs, application/apps/indexer/indexer_cli/src/main.rs, application/apps/indexer/session/src/handlers/export_raw.rs, application/apps/indexer/session/src/handlers/observe.rs, application/apps/indexer/session/src/handlers/observing/mod.rs, application/apps/indexer/session/src/handlers/observing/stream.rs, application/apps/indexer/session/src/operations.rs, application/apps/indexer/session/src/tracker.rs, application/apps/indexer/sources/benches/dlt_producer.rs, application/apps/indexer/sources/benches/macros/mock_producer_multi.rs, application/apps/indexer/sources/benches/macros/mock_producer_multi_parallel.rs, application/apps/indexer/sources/benches/macros/mock_producer_once.rs, application/apps/indexer/sources/benches/macros/mock_producer_once_parallel.rs, application/apps/indexer/sources/benches/someip_legacy_producer.rs, application/apps/indexer/sources/benches/someip_producer.rs, application/apps/indexer/sources/benches/text_producer.rs, application/apps/indexer/sources/src/lib.rs, application/apps/indexer/sources/src/producer.rs, application/apps/indexer/sources/src/producer/tests/cancel_safety.rs, application/apps/indexer/sources/src/producer/tests/multi_parse.rs, application/apps/indexer/sources/src/producer/tests/single_parse.rs, application/apps/indexer/sources/src/sde.rs, cli/chipmunk-cli/src/session/file.rs, cli/chipmunk-cli/src/session/socket.rs
This PR close #2257 
SDE communications are special case that are used in observe sessions only and can be moved to there since producer isn't locked with stream interface anymore. 
This change won't force cancel safety on income method, and ensure that writing to serial ports byte by byte won't be interrupted.
=> Move SDE communication to observe session.

application/client/package.json, application/holder/package.json, changelog.md
- Upgrade DLT parser version
- Add TCP reconnection support
- Refactoring to fit cancel safe requirements
=> Up to 3.16.5

application/apps/indexer/Cargo.lock, application/apps/indexer/plugins_host/Cargo.toml, application/apps/indexer/plugins_host/src/plugins_shared/mod.rs, application/apps/indexer/plugins_host/src/v0_1_0/bytesource/bytesource_plugin_state.rs, application/apps/indexer/plugins_host/src/v0_1_0/bytesource/mod.rs, application/apps/indexer/plugins_host/src/v0_1_0/parser/bindings.rs, application/apps/indexer/plugins_host/src/v0_1_0/parser/mod.rs, application/apps/indexer/plugins_host/src/v0_1_0/parser/parser_plugin_state.rs, application/apps/indexer/plugins_host/src/v0_1_0/shared/mod.rs, application/apps/indexer/stypes/src/plugins/extending.rs, application/apps/rustcore/rs-bindings/Cargo.lock, application/platform/types/observe/origin/index.ts, plugins/README.md, plugins/examples/dlt_parser/src/dlt/fmt.rs, plugins/examples/dlt_parser/src/lib.rs, plugins/examples/file_source/src/lib.rs, plugins/examples/string_parser/src/lib.rs, plugins/plugins_api/README.md, plugins/plugins_api/src/bytesource/mod.rs, plugins/plugins_api/src/lib.rs, plugins/plugins_api/src/parser/mod.rs, plugins/plugins_api/src/shared/mod.rs, plugins/plugins_api/src/shared/sandbox.rs, plugins/plugins_api/wit/v0.1.0/deps/bytesource/world.wit, plugins/plugins_api/wit/v0.1.0/deps/parser/world.wit, plugins/plugins_api/wit/v0.1.0/deps/shared/sandbox.wit, plugins/plugins_api/wit/v0.1.0/deps/shared/world.wit
This PR closes #2237 
It includes:
* Providing method from the host to creates a temporary directory for the plugins on each session with read and write access.
* Wrap the method with better types in `plugins_api` crate for plugins developers.
* Demonstrate the functionality in string parser example.
* Update plugins README
* Final refactoring & Resolve todos
=> Plugins: Provide API for accessing temporary directory

application/apps/indexer/plugins_host/src/parser_shared/mod.rs, application/apps/indexer/session/src/handlers/export_raw.rs, application/apps/indexer/session/src/handlers/observing/mod.rs, application/apps/indexer/sources/src/producer.rs, plugins/examples/dlt_parser/Cargo.lock, plugins/examples/dlt_parser/Cargo.toml, plugins/examples/dlt_parser/src/dlt/mod.rs
This PR:
* Differentiate max allowed consecutive errors limit between parse and incomplete errors after making producer loop dropping one byte at a time for parse errors. For the same reason limits has been increased
* Remove all debug and benchmarking code and all remaining TODOs.
* Dlt plugin: Fix error mapping since dlt unrecoverable error has different meaning in the plugin context.
* Reference latest version of dlt_core in DLT plugin
=> Plugins: Minor Changes & Refactoring & Cleanup

application/apps/indexer/addons/dlt-tools/src/lib.rs, application/apps/indexer/parsers/src/dlt/mod.rs, application/apps/indexer/parsers/src/lib.rs, application/apps/indexer/parsers/src/someip.rs, application/apps/indexer/parsers/src/text.rs
This PR closes #2260 
It includes:
* Providing a trait for parsers who parse one item at a time to be used with the current built-in parsers. 
* The new trait `SingleParser` provides blanket implementation for Parser trait with all types implementing it.
* Apply the new trait on all built-in parsers adjusting their unit tests accordingly.
=> Trait `SingleParser` with blank implementation for Parser

application/client/package.json, application/holder/package.json, changelog.md
- Fix sticky scrolling issue
- Refactoring an infrastructure of parsers
=> Up to 3.16.6

application/apps/indexer/Cargo.lock, application/apps/indexer/plugins_host/Cargo.toml, application/apps/indexer/plugins_host/src/plugins_shared/load.rs, application/apps/indexer/plugins_host/src/v0_1_0/bytesource/mod.rs, application/apps/indexer/plugins_host/src/v0_1_0/parser/mod.rs, application/apps/rustcore/rs-bindings/Cargo.lock, plugins/examples/dlt_parser/Cargo.lock, plugins/examples/file_source/Cargo.lock, plugins/examples/protobuf/Cargo.lock, plugins/examples/string_parser/Cargo.lock, plugins/plugins_api/Cargo.toml
This PR provides:
* Update `wasmtime` and `wit-bindgen` dependencies to the latest versions.
* Provide more details on errors from plugins: `wasmtime` uses `anyhow` to deliver their errors which provides error details in debug print only.
=> Plugins: Update wasmtime dependencies & Errors context

application/apps/indexer/indexer_base/src/config.rs, application/apps/indexer/parsers/src/someip.rs, application/apps/indexer/session/src/state/attachments.rs, application/apps/indexer/sources/src/serial/serialport.rs, cli/development-cli/CHANGELOG.md, cli/development-cli/Cargo.lock, cli/development-cli/Cargo.toml, cli/development-cli/src/release/codesign/macos.rs, cli/development-cli/src/release/compress.rs, cli/development-cli/src/release/mod.rs, cli/development-cli/src/release/paths.rs
This PR provide the following:
* Include chipmunk CLI in release workflow providing additional archive for CLI tool with the name pattern `chipmunk-cli@{cli-version}-{platform}-portable.
* The archive of Chipmunk CLI will be provided in the same release directory to avoid changing release GitHub action.
* Code signing on MacOS still not tested.
@itsmesamster Could you please have a look on the changes for code signing and test them
=> Development CLI: Include Chipmunk CLI in release command.

application/apps/indexer/docs/README.md, application/apps/indexer/docs/plugins.md, application/apps/indexer/docs/producer-plugins.drawio, application/apps/indexer/docs/producer.md, application/apps/indexer/plugins_host/src/plugins_shared/mod.rs
This PR provides developer documentation in Chipmunk Core for the following:
* Message Producer structs and its relations with multiple parser and byte-sources traits.
* Plugins implementation in Chipmunk host.
* A diagram with `drawio` demonstrating Message Producer with all parsers and byte-sources (Built-in and Plugins) and The plugins Manager and Runtime
This PR also provides a small fix to avoid giving read access to the same directory multiple time in a case of multiple files sharing the same parent directory that are needed by the plugin
=> Plugins & Core: Add developer documentation & Small Fix

application/apps/indexer/plugins_host/src/plugins_manager/load.rs, application/apps/indexer/plugins_host/src/plugins_shared/load.rs, docs/plugins/development-guide.md
This PR provides the following:
* Extend Chipmunk Logs with the debug infos for error while loading and validating the plugins.
* Current errors for the UI are intended for users wouldn't contain all the needed informations for plugin developers.
* Provide Documentation for adding the plugins using the Add button in the UI
* Fix paths for adding the plugins manually
* Fix formatting to make it render well in mkdocs
=> Plugins: More Logs & Extend Documentations + Fix Paths

application/client/src/app/ui/tabs/plugins/details/component.ts
This PR adds a confirmation dialog before removing a plugin since this action will remove the plugin permanently.
=> Plugins Manager: Confirmation Dialog on Remove Plugins

application/apps/indexer/Cargo.toml, application/apps/indexer/stypes/Cargo.toml
This PR fixes warnings on cargo.toml files level. Those updates weren't visible in development cli tool so we didn't catch them.
It provides:
* Workspace doesn't have edition config. However it demands to specify which resolve to use.
* Move Proptest profiles configurations because they are allowed on workspace root level only
=> Core: Fix Warnings in Cargo.toml File after update to 2024

application/apps/rustcore/rs-bindings/log4rs.yaml, application/apps/rustcore/rs-bindings/src/logging.rs, docs/contributing/welcome.md, docs/plugins/development-guide.md
This PR closes #2344 
It fixes the logging configuration on the backend providing:
* Change logging configurations as following:
- All rust modules will write logs with level WARN to stdout and to `chipmunk.indexer.log`
- Log files will be truncated at the start to avoid taking space on host machine since log files will never get cleaned up.
- Although it's possible to manage rolling log files with log4rs, it will be effect the performance unnecessarily because it will do
checks after each logs.
- Update version of the log configurations file.
* Introduce version validation in log initialization to ensure old log conifg files will get updated.
* Remove panics on errors in logging code since it will return Result
* Add documentation to logging module.
* Remove unused and commented out code …
=> Logging: Update Configuration + Version Control + Documentation + Cleanp

application/apps/indexer/plugins_host/src/plugins_manager/load.rs, application/apps/indexer/plugins_host/src/plugins_manager/mod.rs, application/apps/indexer/plugins_host/src/plugins_manager/tests.rs, application/apps/indexer/plugins_host/src/plugins_manager/validator.rs, application/apps/indexer/stypes/src/plugins/extending.rs, application/apps/indexer/stypes/src/plugins/proptest.rs
This PR closes #2328 
It provides validations for the configurations and metadata provided by the plugins.
We are checking against the following:
* Plugins configuration items or rendering columns can't be greater than 100 item.
* Plugins configurations ID texts can be greater than 1 Kilobytes.
* Plugins titles, the title of its configuration items or the columns captions can't be greater than 2 Kilobytes.
* Plugins description, the description of the configurations or the rendering columns can't be greater than 10 Kilobytes.
This PR introduces small refactoring regarding moving all validations into one module and some cleaning up. Also it includes unit tests for all new validations
=> Plugins: Validate plugins against invalid or malicious configurations 

application/client/src/app/module/ipc.ts, application/client/src/app/ui/views/sidebar/attachments/preview/image/component.ts, application/holder/package.json, application/holder/src/preload/preload.ts, application/holder/src/service/electron.ts, application/holder/src/service/electron/handles/clipboard.ts, application/holder/src/service/electron/handles/index.ts, application/holder/src/service/electron/protocol.ts, application/holder/yarn.lock, application/platform/package.json, application/platform/types/index.ts, application/platform/types/net.ts
- Extend exposed API with clipboard API
- Switch from browser's clipboard API to native one (in context of images)
- Switch loading of attachment to stream-based
=> Switch to native clipboard API (close #2386)

application/holder/src/loaders/cli.ts, application/holder/src/service/cli/open.ts, application/holder/src/service/cli/stream.ts, application/platform/types/observe/factory.ts, application/platform/types/observe/origin/concat.ts
This PR closes #2403
It provides fixes for the main application CLI interface regarding `files` command:
* Use the provided parser type as CLI argument for opening files from the command line. The previous implementation was ignoring the parser argument entirely.
* Fix files concatenating: Apply file types on all configurations in concatenating origin instead of changing the default only.
* Help text: Set correct application name in CLI help texts.
=> Fix Application CLI for Files: Parser argument ignored & Files Concatenating

.github/workflows/lint_master.yml, .github/workflows/pullrequest_check.yml
GitHub isn't installing clippy by default anymore
=> CI: Ensure Clippy is installed on linting jobs
